### DISCUSSION TITLE
Particular namelist does not want to be edited from esm_runscripts

### DISCUSSION THREAD

**Discussion by JanStreffing** [esm-tools/esm_tools#1055] [ESM-Tools support]
I am modifying namelist of FESOM2 as such:
```

    add_namelist_changes:
        namelist.ice:
            ice_therm:
                albsn: 0.81
                albsnm: 0.77
                albi: 0.6
                albim: 0.43
        namelist.oce:
            oce_dyn:
                k_gm_max: 3000
                k_gm_rampmax: 40.0
                k_gm_rampmin: 30
                scaling_ferreira: true
                scaling_fesom14: true
        namelist.tra:
            tracer_phys:
                kv0_const: false
        namelist.config:
            run_config:
                use_cavity: true
                use_cavity_partial_cell: true
```

I add one more namelist like so:
```

    add_namelist_changes:
        namelist.ice:
            ice_therm:
                albsn: 0.81
                albsnm: 0.77
                albi: 0.6
                albim: 0.43
        namelist.oce:
            oce_dyn:
                k_gm_max: 3000
                k_gm_rampmax: 40.0
                k_gm_rampmin: 30
                scaling_ferreira: true
                scaling_fesom14: true
        namelist.tra:
            tracer_phys:
                kv0_const: false
        namelist.config:
            run_config:
                use_cavity: true
                use_cavity_partial_cell: true
        namelist.dyn:
            dynamics_general:
                use_wsplit: true
```

This crashes with:
```
Run number for internal OpenIFS timekeeping: 1
Traceback (most recent call last):
  File "/home/a/a270092/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270092/esm_tools/src/esm_runscripts/cli.py", line 285, in main
    Setup()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 69, in __call__
    self.prepcompute()
  File "/home/a/a270092/esm_tools/src/esm_runscripts/sim_objects.py", line 161, in prepcompute
    self.config = prepcompute.run_job(self.config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepcompute.py", line 32, in run_job
    config = evaluate(config, "prepcompute", "prepcompute_recipe")
  File "/home/a/a270092/esm_tools/src/esm_runscripts/helpers.py", line 69, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270092/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 141, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/a/a270092/esm_tools/src/esm_runscripts/prepcompute.py", line 187, in modify_namelists
    config[model] = Namelist.nmls_modify(config[model])
  File "/home/a/a270092/esm_tools/src/esm_runscripts/namelists.py", line 300, in nmls_modify
    mconfig["namelists"][namelist].patch(changes)
KeyError: 'namelist.dyn'
```

The namelist is available at `/work/ab0246/a270092/runtime/awicm3-v3.2/SPIN_CAV2/run_13500101-13741231/config/fesom/namelist.dyn`

and it contains all the right blocks and names:

```
&dynamics_visc
visc_gamma0  = 0.003 ! [m/s],   backgroung viscosity= gamma0*len, it should be as small a s possible (keep it < 0.01 m/s).
visc_gamma1  = 0.1   ! [nodim], for computation of the flow aware viscosity
visc_gamma2  = 0.285 ! [s/m],   is only used in easy backscatter option
visc_easybsreturn= 1.5

opt_visc     = 5
! 5=Kinematic (easy) Backscatter
! 6=Biharmonic flow aware (viscosity depends on velocity Laplacian)
! 7=Biharmonic flow aware (viscosity depends on velocity differences)
! 8=Dynamic Backscatter

use_ivertvisc= .true.
/

&dynamics_general
momadv_opt   = 2       ! option for momentum advection in moment only =2
use_freeslip = .false. ! Switch on free slip
use_wsplit   = .false. ! Switch for implicite/explicte splitting of vert. velocity
wsplit_maxcfl= 1.0     ! maximum allowed CFL criteria in vertical (0.5 < w_max_cfl < 1.)
                       ! in older FESOM it used to be w_exp_max=1.e-3
ldiag_KE=.false.       ! activates energy diagnostics
/

```

Any idea why this happens?

**Comment by nwieters** [comment]
Hi @JanStreffing, I was able to reproduce this error. I will have a closer look.

**Comment by nwieters** [comment]
Hi @JanStreffing,
in my testrun I noticed that in the finished_config.yaml, there is an additional textstring in the entry for the namelist.dyn: &id002
```
fesom:
    add_namelist_changes:
        namelist.dyn: &id002
            dynamics_general:
                use_wsplit: true
```
Is this true in your case as well? 
I will try to figure out where this string comes from.

**Comment by nwieters** [comment]
Hi @JanStreffing,

I think the &id002 is not the problem. These are references.

To solve the issue partly, I needed to put the following into the configs/setups/awicm3/awicm3.yaml:
```
fesom:
...
    choose_general.major_version:
    ...
        "v3.1":
        ...
            add_namelists:
                - namelist.dyn
            add_config_sources:
                dyn:     "${namelist_dir}/namelist.dyn"
            add_config_in_work:
                dyn:     "namelist.dyn"
            add_config_files:
                dyn:     dyn
```
In my runscript I put:
```
fesom:
....
    add_namelist_changes:
        namelist.dyn:
            dynamics_general:
                use_wsplit: true
```
But then I get a namelist.dyn in run_.../work/ that only has this entry. I guess this is not how it should be.
