### DISCUSSION TITLE
FESOM2 comp_command overwrite

### DISCUSSION THREAD

**Discussion by JanStreffing** [esm-tools/esm_tools#1065] [ESM-Tools support]
I tried to overwrite the FESOM2 comp_command from the fesom-2.0.yaml. This does not seem to work. I need to be able to controll the parallel compile threads N in "-j N" of the comp command. On some maschines using all threads on the login not does not work. (atmos, duru(KMA)). 

I tried putting a comp_command in the yaml but it was just ignored.:

```
  2.0-frontiers:
    branch: awicm-3-frontiers_parallel-restart
    destination: fesom-2.0
    git-repository:
    - https://github.com/FESOM/fesom2.git
    comp_command: "mkdir -p build; cd build; cmake -DOIFS_COUPLED=ON -DFESOM_COUPLED=ON ..;   make install -j 8"
```
