### DISCUSSION TITLE
JSBACH "dynveg" in AWIESM

### DISCUSSION THREAD

**Discussion by ackerlar** [esm-tools/esm_tools#1114] [ESM-Tools support]
I just recognized, that the **use_dynveg** in `namelist.jsbach` is always set to `True` for AWI-ESM in `configs/setups/awiesm/awiesm.yaml`. As I understand, the usage of dynamic vegetation is the (main) difference between AWI-CM and AWI-ESM, I find it somewhat misleading and unintuitive that there is the **dynamic_vegetations** flag that controls the namelist directories for JSBACH but not the actual namelist entries.

I changed this setting in `configs/setups/awiesm/awiesm.yaml` (#https://github.com/esm-tools/esm_tools/commit/681bcf7924f895003c2143cf21dd5b359ad27da3) but I am not sure how reasonable that is.

**Comment by mandresm** [comment]
Hi @ackerlar,

You can see that it's defined as `True` by default in https://github.com/esm-tools/esm_tools/commit/681bcf7924f895003c2143cf21dd5b359ad27da3#diff-12db65fd0e5c14c8c3bef16672a0137ca33026004049cf1eb5334ba81bf03860R246

The reason why it's configured in this way is in case someone wants to deactivate it can simply do in the runscript.yaml:
```yaml
jsbach:
    dynamic_vegetations: False
```
instead of
```yaml
jsbach:
        add_namelist_changes:
                namelist.jsbach:
                        jsbach_ctl:
                            use_dynveg: False
```

So I'd recommend to leave it as it was because by default is True already.
