### DISCUSSION TITLE
Run experiments with two branches

### DISCUSSION THREAD

**Discussion by fernandadialzira** [esm-tools/esm_tools#609] [Models] [answered]
For my bootstrap experiments, I had to use the `ice` branch of `ECHAM`, as the main `wiso` would give me repeated errors with missing binaries. Now, I would like to continue the experiment from this bootstrap, however, using `wiso`. 

Machine: `mistral`
Model: `awiesm-2.1-wiso`
esm-tools branch: `release`

To do so, is it correct to?
1. `git checkout wiso` on echam
2. Apply branch-off instructions from echam and fesom as:

```
echam:
    lresume: 1
    version: "6.3.05p2-wiso"
    ini_parent_exp_id: glac1d21_classic_001
    fake_initial_date: "2001-01-01"
    ini_parent_date: "$(( ${fake_initial_date} - ${echam.time_step}seconds ))"
    ini_parent_dir: "${general.project_base}/experiments_bootstrap/glac1d21_classic_001/restart/echam/"
    restart_rate: 1
    restart_unit: "years"
```
```
fesom:
    lresume: True
    ini_parent_exp_id: glac1d21_classic_001
    ini_parent_date: "2000-12-31"
    ini_parent_dir: "${general.project_base}/experiments_bootstrap/glac1d21_classic_001/restart/fesom/"
    restart_rate: 1
    restart_unit: "y"
    restart_first: 1
```
