### DISCUSSION TITLE
how to make a time/year change in restart?

### DISCUSSION THREAD

**Discussion by PengyangSong** [esm-tools/esm_tools#650] [ESM-Tools support] [answered]
Hi there,
I have an LGM run which ends at some year like 27**, I want to restart this but with a MIS6 orbital forcing to spinup.
I think all other settings are clear, but I want to change this spinup progress starting from year 0001. Can this be set by yaml file? or do I need to do something manually like "cp fesom.2700.* fesom.0000.*"
Thanks.

**Comment by denizural** [comment, marked as answer]
Hi @PengyangSong,

If I understood you correctly, you want to restart from 0001 and not 2700. Then, I would go to the `restart/` directory of your parent simulation and copy the required files that new simulation needs to another directory. Eg.
```shell
mkdir restarts_0001
cp <list of restarts files with 27XX> restarts_0001
cd restarts_0001
mv <file ending with 27XX> <file ending with 0001>
```

You also need to set some variables in your runscript:

```yaml
general:
    lresume: True                                                              # we are making a restart
    ini_parent_dir: "/path/to/your/restarts_0001 directory"
    ini_restart_dir: "${general.ini_parent_dir}"
    ini_parent_exp_id: <old-experiment-id>
    ini_parent_date: "0001-MM-DD"                                              # day when your parent simulation ends
    initial_date: "YYYY-MM-DD"                                                 # start of your new simulation
```

There is a section in our documentation that can also help you:
https://esm-tools.readthedocs.io/en/latest/cookbook.html#how-to-setup-runscripts-for-different-kind-of-experiments

Please make a check (`--check`) run first and for more information redirect the verbose output to a file. Eg.
`esm_runscripts -e myrun myrunscript.yaml  --check --verbose &>output.txt`
`output.txt` will contain all sources and targets of files used.

I hope this helps. 
Best,
Deniz
