### DISCUSSION TITLE
How do I have slurm send me an email about crashed runs in esm_tools?

### DISCUSSION THREAD

**Discussion by JanStreffing** [esm-tools/esm_tools#685] [ESM-Tools support] [answered]
I would like to get an email from slurm in case my run crashes. How do I make that happen via esm_tools yaml runscripts?

**Comment by denizural** [comment, marked as answer]
Hi @JanStreffing,
Does this help:
```yaml
computer: 
    mail_type: FAIL
    mail_user: "fizz@buzz.com"
```
PS: edited the typo in the question
