### DISCUSSION TITLE
Restart Run with AWI-CM1 in Levante - Missing files??? (I don't think so)

### DISCUSSION THREAD

**Discussion by antoniofis10000** [esm-tools/esm_tools#730] [ESM-Tools support]
Dear ESM-Tools developers.
I am trying to run a restart run using AWI-CM1 and the SSP370 scenario (including spectral nudging) and after running
/work/ab0995/a270148/Prueba.yaml (trying to adapt some runscript I have found in github) I get the following error:

```
ERROR: Missing Configuration
----------------------------
The input file variable amipsst of forcing_sources can not be fully resolved:

/pool/data/ECHAM6//input/r0007/T127/amip/T127_amipsst_@YEAR@.nc:
    from: 1870
    to: 2016
```

I am a bit confused. Is it trying to run an AMIP simulation? (We do not want to run this kind of experiment). Nevertheless, It seems the files can be found in this folder.
What is happening?

Thanks in advance.
Best wishes,
Antonio.

**Comment by denizural** [comment]
Hi @antoniofis10000 could you please write the version of your ESM-Tools. Ie. `esm_tools --version`

**Reply by antoniofis10000** [reply]
Hi @denizural.
Sorry, my version is:
esm_tools, version 6.11.4

Thanks.

**Reply by denizural** [reply]
Hi @antoniofis10000,
Please note that the scenarios are case sensitive. You are mixing ssp370 and SSP370. The correct naming is the lowercase one. Could you please try with the lowercase one.

**Reply by antoniofis10000** [reply]
Hi @denizural.
OMG, thanks for pointing out this dummy mistake.
Now it seems it reads these files.
However, now there are some issues with the JSBACH component (It tries to read some missing files). I have tried to add also a "scenario" (line 113) and change to dataset r0010 (line 114, as I was using in my old runs in Mistral). It still not working.

Thanks.
Best wishes,
Antonio.

**Comment by denizural** [comment]
Hi @antoniofis10000,
Is it working now? Are you still trying to run your simulation with your runscript `Prueba.yaml`?

**Reply by antoniofis10000** [reply]
Hi Deniz.
Not, when I try to run the runscript "Prueba.yaml" (located in: /work/ab0995/a270148) It says:
ERROR: Missing Configuration
----------------------------
The input file variable LU_HIST of forcing_sources can not be fully resolved:

/pool/data/JSBACH/input/r0010/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc:
    to: 1850
/pool/data/JSBACH/input/r0010/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_@YEAR@.nc:
    from: 1851



Thanks.
Best wishes,
Antonio.

**Comment by denizural** [comment]
Hi @antoniofis10000,
I solved this issue mostly. There are some missing files and I am currently fixing your runscript to find them.

**Comment by denizural** [comment]
Hi @antoniofis10000,
I solved this issue mostly. There are now a very few missing files and I am currently fixing your runscript to find them.
This morning we made a meeting with @mandresm and decided to make a meeting with three of us. We need your guidance for the input files in the `pool/` directory. Would you be available today for a quick meeting?

**Reply by antoniofis10000** [reply]
Hi @denizural .
Thanks so much.
I am available today until 11:00, and then ~12:15-16:30
So, please, let me know when it works better for you.

Thanks again.
Best wishes,
Antonio.

**Comment by denizural** [comment]
Hi Antonio, we can meet at 12:15. I am sending you a detailed mail soon.

**Comment by antoniofis10000** [comment]
Dear Developers.
I made some changes in the runscript (/work/ab0995/a270148/PruebaDeniz.yaml) (I added Ndepo to remove_jsbach.forcing_files) as well as in the /work/ab0995/a270148/ESMTOOLS7July2022/esm_tools/configs/components/jsbach/jsbach.datasets.yaml (                        "LU_hist_scenario": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/no_LUH_transitions_T127.nc"). As well as I have changed the symbolic links in the oasis and hdmodel (in the last one a change in the name of file is needed, so I created a hdmodel2 folder in the restart folder).

(We also copied yesterday the default namelist from the old ESM-Tools).

After running this runscript (e.g. Prueba14July1743) there still being some missing files:
- missing source: /pool/data/ECHAM6/input/r0008/T127/greenhouse_ssp370.nc

This file seems to be in: /pool/data/ECHAM6/input/r0008 (without the resolution).

- missing source: /work/ab0995/a270148/ESMTOOLS7July2022/esm_tools/awicm-CMIP6/bin/echam6

This file seems to be in: /work/ab0995/a270148/ESMTOOLS7July2022/esm_tools/awicm-CMIP6/echam-6.3.04p1/src/echam/bin

- missing source: /work/ab0995/a270148/ESMTOOLS7July2022/esm_tools/awicm-CMIP6/bin/fesom
This file seems to be in: /work/ab0995/a270148/ESMTOOLS7July2022/esm_tools/awicm-CMIP6/fesom-1.4/bin

So probably these inputs are easy to obtain?

Best wishes,
Antonio.

**Reply by antoniofis10000** [reply]
Dear developers.
Is there any update on these issues?
Thanks.

Best wishes,
Antonio.

**Comment by mandresm** [comment]
Dear Antonio,

This should have been fixed by now with version 6.13 where AWICM1-REcoM support was added, together with generalized support for AWICM1 SSP scenarios.

To use the ssp scenarios you'll need to define the following in your runscript:
```
general:
    scenario: ssp<num>
```

We prepared this for T63 resolution. It might be that some files are missing for T127. If that's the case please let me know, we will need to prepare those files, but we can follow the method that @chrisdane used. I'll be at AWI today, let me know if you are around.

**Reply by antoniofis10000** [reply]
Dear Miguel,
Thanks for the update!. It seems that now all the files can be read (I had to transfer also the grids, masks... files to the restart folder, but I think it is ok).

Nevertheless, some issues seem to remain as the run stop after a few seconds (see, for example, /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/Prueba10August1157), probably related to the old namelist.echam (that need to be also copied in the new version, I think) (I tried to eliminate the putdata line, but then the simulation still not working  /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/Prueba10August1159). Probably there are some incompatibilities between the old and new version?

Today I am not at AWI but if needed I can be there in ~15'.
Thanks in advance.
Best wishes,
Antonio.

**Reply by mandresm** [reply]
no worries, no need to come over, I'll look at this after lunch

> (I had to transfer also the grids, masks... files to the restart folder, but I think it is ok).

do you have manually copied things into the experiment folder?

**Reply by antoniofis10000** [reply]
Cool! Thanks so much!
Yes, I needed to copy:
rmp_feom_to_atmo_DISTWGT.nc
rmp_atmo_to_feom_DISTWGT.nc
rmp_atmo_to_feom_BICUBIC.nc 
areas.nc
grids.nc
masks.nc
from the post_ folder to restart/oasis3mct in the old experiment (e.g. /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/From20172019in2017Climatessp3701)
(These files were generated during the run in the old tools)

Best wishes,
Antonio.

**Reply by mandresm** [reply]
I see, so no copying manually into the new experiment folder. That's good.

I'll be looking at your script in the next hour and add comments here about it, that should help you to resolve the problems.

**Comment by mandresm** [comment]
Please see my comments below and let us know how it goes.

```yaml
general:
    setup_name: "awicm"
    version: "CMIP6"
    account: "ab0995"
    scenario: "ssp370"
    compute_time: "07:59:00"
    initial_date: "2019-01-01"
    final_date: "2019-03-01"
    use_database: false
    base_dir: "/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/"    # deniz: open in the original
    #base_dir: "/work/ab0995/a271096/Solutions/Antonio/"                              # deniz: my version
    nyear: 0
    nmonth: 3
    nday: 0
    lresume: true
    ini_parent_exp_id: "From20172019in2017Climatessp3701"
    # deniz: commented out ini_parent_dir and using my version
    ini_parent_dir: "/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/From20172019in2017Climatessp3701/restart/"
    # ini_parent_dir: "/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/From20172019in2017Climatessp3701/"  # deniz: using this one instead
    ini_parent_date: "2018-12-31"
```
Unless you have a good reason to not do it (restarting from a different date than the previous one), use `ini_parent_date: ${prev_date}` feature variable.
```yaml
    use_venv: false
    first_initial_year: "${general.initial_date!syear}"

awicm:
```
You don't need this section, all that is in `awicm` can go in `general`. The duplicates can be remover.
```yaml
    version: "CMIP6"
    scenario: "ssp370"
    post_processing: 0
    model_dir: "/work/ab0995/a270148/ESMTOOLS10August2022/esm_tools/awicm-CMIP6/"
    pool_dir: "/pool/data/"
    resolution: "T127"

fesom:
    restart_rate: 3
    restart_unit: "m" 
    restart_first: 3
    pool_dir: "/work/ab0995/a270152/testing_pool/input/"
```
Please, don't use my personal testing pool. The pools are now fixed for the mesh distributions. You can remove this last line.
```yaml
    mesh_dir: "/work/ab0995/a270152/testing_pool/AWICM/FESOM1/MESHES/core/"
```
Please, don't use my personal testing pool. Use this one instead `mesh_dir: "/pool/data/AWICM/FESOM1/MESHES/core/"`
```yaml
    lresume: "${general.lresume}"
    ini_parent_dir: "${general.ini_parent_dir}/fesom/"
    ini_parent_exp_id: "${general.ini_parent_exp_id}"
    ini_parent_date: "${general.ini_parent_date}"   
    resolution: "CORE2"
    time_step: 450 
    nproc: 384 

echam:
    dataset: r0008    # deniz
    scenario: "ssp370"
    resolution: "T127"
    levels: "L95"
    lresume: "${general.lresume}"
    restart_unit: "months"
```
You are telling ESM-Tools to restart every three months, and the same goes for FESOM, you probably want to set `restart_rate: 3` here as well. I know you might want to produce restarts files every month while doing actual restarts every 3 months, but I say for now let's keep things simple, and then we can complicated once the simulation can restart successfully.
```yaml
    ini_parent_dir: "${general.ini_parent_dir}/echam/"
    ini_parent_exp_id: "${general.ini_parent_exp_id}"
    ini_parent_date: "${general.ini_parent_date}"  

    post_processing: False
    nproca: 32
    nprocb: 32
```
For `fesom.nproc` and `echam.nproca/nprocb` @chrisdane ran this benchmarks for `CORE` and `T63`: https://github.com/esm-tools/esm_tools/discussions/663#discussioncomment-3267682. You can use them as a guideline to request more or less computing resources. To me it looks like if you want a jump in speed you need to allocate 512 cores to FESOM
```yaml
    time_step: 200 
    namelist_changes:
        namelist.echam:
            runctl:
                lnudge: ".true."
                putdata: "1,'hours','first',0"
                NPROMA: "remove_from_namelist" 
         [...]

jsbach:
    # dataset: r0008    # deniz
    version: "3.20p1"                      # deniz
```
Comment the version here, I think you want to be using the default `version: "3.20"`.
```yaml
    lresume: "${general.lresume}"
    ini_parent_dir: "${general.ini_parent_dir}/jsbach2/"
    ini_parent_exp_id: "${general.ini_parent_exp_id}"
    ini_parent_date: "${general.ini_parent_date}"   
    # scenario: "ssp370"                   # deniz: commented out
    # dataset: r0010                       # deniz: commented out
```
you probably want to add the following instead of manually modifying the `jsbach.dataset.yaml` (see the comment at the bottom of this message on `LU_trans modifications`):
```yaml
    add_forcing_files:
        LU_trans: LU_trans_none
    streams:
        - jsbach
        - jsbid
        - yasso
        - surf
        - veg
    remove_jsbach.forcing_files:
        - a_nd_file
        - lightning
        - popdens
        - Ndepo
hdmodel:
    lresume: "${general.lresume}"
    ini_parent_dir: "${general.ini_parent_dir}/hdmodel2/"
    ini_parent_exp_id: "${general.ini_parent_exp_id}"
    ini_parent_date: "${general.ini_parent_date}"  



oasis3mct:
    cf_name_dir: "${general.model_dir}/oasis"
    cf: "${cf_name_dir}/cf_name_table.txt"
    lresume: "${general.lresume}"
```
Since you are using different number of MPI tasks and FESOM mesh distributions to run this simulation in comparison with the parent experiment, you want to set `oasis3mct.lresume: false`. Otherwise, the model will blow up due to numerical instabilities, product of incorrect oasis-fluxes indexing for the new mesh. If you manage to plot something with `lresume: true` before the experiment blows up it will look like something crazy like this:

![image](https://user-images.githubusercontent.com/63242832/183926835-ad9bef5f-dc63-49d6-99e6-4359539dce9e.png)
First reported and image produced by @chrisdane 

LU_trans modifications
-----------------------
> I made some changes in the runscript (/work/ab0995/a270148/PruebaDeniz.yaml) (I added Ndepo to remove_jsbach.forcing_files) as well as in the /work/ab0995/a270148/ESMTOOLS7July2022/esm_tools/configs/components/jsbach/jsbach.datasets.yaml ( "LU_hist_scenario": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/no_LUH_transitions_T127.nc")

You don't need to change the config file. You just need to select another file in your runscript, inside `add_forcing_files` in this case that file is tagged `LU_tras_none`:
```yaml
jsbach:
    add_forcing_files:
        LU_trans: LU_trans_none 
```

What you are effectively doing is deviating from the default for `cmip6` scenario types defined here:
https://github.com/esm-tools/esm_tools/blob/bf7c9100f8e9f6883469cc3ac077c53dd4c6e79f/configs/components/jsbach/jsbach.yaml#L302-L312

Resources
----------
For better understanding how to use the file dictionaries you can go through the ppts/pdfs of the workshop, chapter `7.1_file_dictionaries`:
https://github.com/esm-tools/workshops/tree/main/202207_AWI_ESM-Tools/docs/ppt
For clarifying exercises with solutions check this out:
https://github.com/esm-tools/workshops/blob/main/202207_AWI_ESM-Tools/exercises/7.1_file_dictionaries.md

**Comment by mandresm** [comment]
Hi Antonio,

You'll need to `git pull` in the branch `fix/echam_default_namelists_ssp` to get an update I made there.

**Comment by antoniofis10000** [comment]
Hi Miguel.
Thanks for all the updates.
It still not working (see for example /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/Prueba10August1923).

Thanks in advance.
Best wishes,
Antonio.

**Reply by mandresm** [reply]
there is a problem with the namelist:
```
   0: forrtl: severe (64): input conversion error, unit 100, file /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/Prueba10August1923/run_20190101-20190331/work/namelist.echam, line 19, position 1
```
Investigating the issue now...

**Reply by mandresm** [reply]
In your runscript, in `echam.namelist_changes`, `putdata` and many other namelist variables are defined as `putdata: "1,'hours','first',0"`. This is a string and so it is passed to the namelist, and ECHAM complains. It needs to be a list and for that you'll need the following: `putdata: [1,'hours','first',0]`. You need to follow that logic for all the variables containing lists that you added to the `namelist_changes`. And by the way, it is a good practice to always use `add_namelist_changes` in the runscript, instead of `namelist_changes` to make sure your changes there win over any other's file.

**Reply by antoniofis10000** [reply]
Ups. Thanks for highlighting the mistake.
Once these changes are made as well as the line 122 in mo_nudging_constants.f90 are changed (INTEGER,PARAMETER :: nmaxc = 80 to INTEGER,PARAMETER :: nmaxc = 95) (and the model is recompiled) I think it is not able to read the restart file related with nudging (_nudg). Is it copied by ESM-Tools?

Thanks in advance.
Best wishes,
Antonio.

**Reply by mandresm** [reply]
That file doesn't exist, that's the problem, and I don't think it has to be copied by ESM-Tools.

**Reply by mandresm** [reply]
I think the problem is that your file is `/work/ab0995/from_Mistral/ab0995/a270148/ERA5/Nudging/era5_T127L95_%Y4%M2.nc`. This `%Y4%M2 syntax means nothing to the new ESM-Tools. Instead, you can use the time variables syntax described in this chapter of the workshop and exercises:
Theory: https://github.com/esm-tools/workshops/blob/main/202207_AWI_ESM-Tools/docs/pdf/6.2_maths_calendar_operations.pdf
Exercise: https://github.com/esm-tools/workshops/blob/main/202207_AWI_ESM-Tools/exercises/6.2_math_calendar_operations.md

Hint: the answer to your problem is most likely: `/work/ab0995/from_Mistral/ab0995/a270148/ERA5/Nudging/era5_T127L95_${start_date!syear!smonth}.nc`

**Reply by antoniofis10000** [reply]
I think these _nudg files are needed (check for example /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/Prueba10August1521/run_20190101-20190331/work/echam.stderr). They have the same file structure as g3b1hi, g3bday,... e.g.: /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/From20172019in2017Climatessp3701/restart/echam).

Ok, sorry for the mistake, do we have some """"moving date variable"""?. As for example if we want to run a simulation from 01/01/2017 to 31/09/2019 for August 2018 both year and month will be different from start_date (or finish date or previous date).

Even we use probably not the right nudging files the model still not running due to the missing restart files.
Thanks in advance.
Best wishes,
Antonio.

**Reply by mandresm** [reply]
ESM-Tools does not have a moving date variable, but I am now guessing that maybe this "%Y4%M2" is ECHAM internal and therefore you can leave it.

**Comment by mandresm** [comment]
and another update, it seems that the `hydrography`, `forcing`, `pool-data` folders for FESOM1 do not exist in the `Levante` pool, so again a pool issue...

You'll need to figure out where the FESOM1 climatedatapath is in Levante, certainly not in the pool. You can check what were you using in your older simulation and that might give you a clue. And it will be great if we can fix this issue for at least this set of files meaning that if we find the files that are not in the pool, but should be, we should make sure that after this the files get into the pool.

I make a note about this missing file in the document for tracking the pool issues: https://notes.desy.de/CDjxNh7NRa6xqtuDX8pS6w#

**Comment by antoniofis10000** [comment]
Dear Developers.
Is there any update about this issue?
Thanks.
Best wishes,
Antonio

**Reply by mandresm** [reply]
I understood the main problem was something weird going on in ECHAM on loading the nudging files. This doesn't seem an ESM-Tools issue to me, but it would help if you report the error that you get in the `log` file.

**Reply by antoniofis10000** [reply]
Hi Miguel.
Yes, at least is the point where the model stops. I am not sure if the issue is related with ECHAM or ESM-Tools but in the prehistoric version of ESM-Tools this file is properly copied (and used I think).
The error can be seen for example in:/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/Prueba10August1521/run_20190101-20190331/work/echam.stderr.
It says:
inquire_rerun_file: restart_Prueba10August1521_nudg.nc - No such file or directory
 IO_open failed on: restart_Prueba10August1521_nudg.nc
 IO_open  : error status = 2
 IO_INQ_DIMID: lat
 IO_INQ_DIMID: NetCDF: Not a valid ID
FATAL ERROR in IO_INQ_DIMID: Run terminated.
 FINISH called from PE: 0


Thanks.

**Reply by mandresm** [reply]
I see, so files need to be copied. This is something that needs to be implemented then in your runscript (or even in `echam.yaml`). The first question is that do you consider nudging files `forcing` or `input` files?

**Reply by antoniofis10000** [reply]
Related to nudging there are two types of files (probably there are issues with both of them). To be honest, I do not know the exact difference between "forcing" and "input" files.
The first one is a restart file needed to run the simulation (in ECHAM, in addition to the "classical" accw,aclcim,co2,echam,g3b1hi,... we need this _nudg file). Probably in the new tools some new command is needed, but it was not the case in the old ones (see for example /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/From20172019in2017Climatessp3701/scripts/scriptE12017.run). This file is read when the simulation starts and when we did different runs with the same runscript (for example we want to run a year with restarting every 3 months) it was readed automatically.

The second one is the data needed to do the nudging (data from ERA5 after some post-processing done at MPI); the structure required in the old tools was one file per month (only January 2017) with all fields; the structure of the data have to appear in the runscript in the ndg_file_nc command. In the old tools, we used the "%Y4$M2" structure to point that different files need to be readed (as for example in this runscript the simulations spanned from 01/01/2017-30/09/2019). (So, probably this point can also be problematic).

Is everything clear? Sorry for not be able to give you more details.

Best wishes,
Antonio.

**Comment by mandresm** [comment]
I think I know what is happening, but a clarification first:

> The first one is a restart file needed to run the simulation (in ECHAM, in addition to the "classical" accw,aclcim,co2,echam,g3b1hi,... we need this _nudg file). Probably in the new tools some new command is needed

In the new tools files are independent of the tools themselves. There is no special cases, you need to define the behavior for those files either in the `echam.yaml` if this is going to be something for everyone to use, or in your `runscript`. I would start doing it in the runscript.

I'll try to upload the videos of the ESM-Tools workshop asap. I would advice to check the complete workshop once it is available, attend the next live workshop or read the documentation (specially the [YAML syntax chapter](https://esm-tools.readthedocs.io/en/latest/yaml.html)).

Issues
=====
Missing Restart file
-------------------
As you said `_nudg` is a restart file and needs to be copied into the work directory. Normally, to add a new restart file you'll need to use the `restart_in_source`, `restart_in_in_work`, `restart_out_source`, `restart_out_in_work`, and `restart_files` in combination with the `add_` functionality, inside your runscript, under the `echam` section. However, luckily for you `echam.yaml` is configured in a way that does this all automatically for you just by modifying the `streams` variable:
https://github.com/esm-tools/esm_tools/blob/75b3086040b43609829b9efb92fee1b16b7c2c27/configs/components/echam/echam.yaml#L685-L702
In essence what `"[[streams-->STREAM]]"` does is to loop through all the `streams` and create the file variables needed for them `<stream_key>: <path>`

In principle, the only thing you'll have to do in your runscript is adding the following:
```yaml
echam:
    add_streams:
        - nudg
```

I strongly recommend that you become familiar with the file dictionaries (`restart_in_source`, `restart_in_in_work`, ...), as I guess you are going to be using them quite a lot. You can go through the ppts/pdfs of the workshop, chapter 7.1_file_dictionaries and the [YAML syntax chapter](https://esm-tools.readthedocs.io/en/latest/yaml.html):
https://github.com/esm-tools/workshops/tree/main/202207_AWI_ESM-Tools/docs/ppt
For clarifying exercises with solutions check this out:
https://github.com/esm-tools/workshops/blob/main/202207_AWI_ESM-Tools/exercises/7.1_file_dictionaries.md

Potential input file problems
----------------------------
> The second one is the data needed to do the nudging (data from ERA5 after some post-processing done at MPI); the structure required in the old tools was one file per month (only January 2017) with all fields; the structure of the data have to appear in the runscript in the ndg_file_nc command

I doubt that this is handled by ESM-Tools prehistoric version at all, because it's on the namelist and it uses dates that tick forward within the model, ESM-Tools in any of its version doesn't know anything about the internal timing of the model after the model finishes its run. You are giving to ECHAM the path to those files through the namelist and ECHAM probably understands how to substitute `%Y%M`

**Reply by antoniofis10000** [reply]
Hi Miguel.
The suggested changes seem to work.
However, the model now stops in a following step. (It says something related to a keyword error detected, but I cannot find where the mistake is located).
I have tried to run the model with (/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/WithNudging18August0956) and without (/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/WithoutNudging18August0950) with the same error (I think).

Thanks!.

**Reply by mandresm** [reply]
The core dumped error by ECHAM seems a lot like a hardware problem to me. When did you run this simulations?

**Reply by antoniofis10000** [reply]
The same error was obtained yesterday afternoon and today ~10:00

**Reply by mandresm** [reply]
Please, use `${prev_date}` here:
```
general:
    ini_parent_date: ${prev_date}
```
This includes hours, minutes and seconds and those are needed for restarting. I don't think this will solve the current problem but it will avoid future errors

**Reply by mandresm** [reply]
are you getting any file missing during submission? If you do can you post them here?

**Reply by antoniofis10000** [reply]
Changed the ini_parent_date and same error is obtained.
There are not missing files during submission.

Thanks.

**Reply by mandresm** [reply]
please, comment this, it's kind of dangerous unless you really know very well the jsbach.yaml and echam.yaml:
```yaml
jsbach:
    #version: 3.20
```

**Reply by mandresm** [reply]
I think the problem you are having is with this incorrect syntax:
```yaml
fesom:
    restart_unit: "months"
```
For FESOM namelists, the `restart_unit` needs to be `"m"` instead.

**Reply by antoniofis10000** [reply]
No differences I think (/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/WithoutNudging18August1406) (PruebaNoNud.yaml runscript)

**Reply by mandresm** [reply]
In my tests I get the same, but please keep those changes in your runscripts as for not doing so will generate new problems after we solve this one. Another issue:
```yaml
oasis3mct:
     #cf_name_dir: "${general.model_dir}/oasis"
    #cf: "${cf_name_dir}/cf_name_table.txt"
```

Please , comment or even better remove these variables, the second does nothing, the first has the potential to break oasis very badly.

**Reply by antoniofis10000** [reply]
Commented and same results are obtained. (/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/WithoutNudging18August1450)

**Reply by mandresm** [reply]
Same for me. I tried with a cold start for all the models `lresum: false` and the error does not occur anymore. This tells me that there is a missmatch in the configuration of the two simulations, the old one, and the restarted one. At this point, the only idea I have is to compare namelists and namcouple, one by one and see if there are any differences that could lead to this problem.

**Reply by mandresm** [reply]
What mesh were you using for your old simulation?

**Reply by antoniofis10000** [reply]
I think we used GLOB (instead of CORE2 in the .yaml run in the previous experiments using the new tools).
I have changed it but I think some files are missing in the pool?????? (see /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/WithoutNudging18August1520/)

**Reply by mandresm** [reply]
Yeah, i don't think you can change mesh for a restart. Things will break. We need to use the glob mesh and find the missing files

**Reply by mandresm** [reply]
Luckily, the old distribution you were using (1920) is multiple of 128, so you can keep using that one. If you'd want to run with less tasks (512) we could generate the distributions for that.

**Reply by antoniofis10000** [reply]
Not able to catch the last point (What does it mean?)

**Reply by mandresm** [reply]
nproc defines in how many MPI tasks the FESOM simulation is going to be divided into. The given mesh, in this case GLOB, needs to be partitioned accordingly so that the MPI task of FESOM can access its respective mess elements. Even if it's the same mesh, you need different mesh partitioning folders depending on the number of MPI tasks you use (e.g. `ls /pool/data/AWICM/FESOM1/MESHES/core/dist`). Glob (`ls /pool/data/AWICM/FESOM1/MESHES/glob/dist`) only has a mesh partitioning for `1920p`, so trying to run with `nproc: 512` will fail. You can create mesh partitions yourself by following the instructions in this file: `/pool/data/AWICM/FESOM1/MESHES/core/dist/README.rst`. That's if you would want to be able to run with smaller number of FESOM nproc.

**Reply by mandresm** [reply]
Do you know where all these files come from? `ls /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/From20172019in2017Climatessp3701/input/echam/`

**Reply by mandresm** [reply]
Never mind, I found the folder `/pool/data/AWICM/FESOM1/MESHES/glob/tarfilesT127/input/echam6/`

**Reply by mandresm** [reply]
No more files missing when you set all of this:
```yaml
fesom:
    nproc: 1920
    resolution: GLOB
    mesh_dir: /pool/data/AWICM/FESOM1/MESHES/glob/
```
