### DISCUSSION TITLE
How to use heterogeneous parallelization with the taskset approach

### DISCUSSION THREAD

**Discussion by mandresm** [esm-tools/esm_tools#759] [ESM-Tools support]
This answers the question of @khimstedt asked during the 02.08. Developer's meeting:

In order to activate Heterogeneous Parallelization using taskset one needs to add the following to the runscript:

```yaml
computer:
    taskset: true # this one activates taskset approach when any model's omp_num_threads>1

<model>:
    omp_num_threads: <number_of_omp_threads> # This one is independent of the approach, it is used both for taskset and hetjobs approach
```

Please, @khimstedt let us know if you find any issues.
