### DISCUSSION TITLE
Specifying resource allocation for a component running as a Julia script

### DISCUSSION THREAD

**Discussion by jannitzbon** [esm-tools/esm_tools#925] [ESM-Tools support]
**Describe the problem you are facing**
I am setting up a new model component (permafrost module "cryogrid") which is implemented in Julia. I need a way to tell both slurm (via esm-tools) and julia how many resources should be used for the model execution. (Ideally, it should be using all available cores of one prod node.) 
Usually model is executed by running a Julia script to which the number of parallel workers is passed as an argument via the option -p:
`$ julia -p 16 script.jl ...`
This works perfectly in interactive mode, e.g. by requesting resources on a node via `$ salloc --min-cpus=16`.
However, it is more tricky using esm-tools. My attempts so far:

- Initially, I passed the variable `nproc=16` to the execution command, but that resulted in the execution startion on 16 cores, each trying to start 16 parallel workers.

- I then defined a variable `nproc_julia=16` which is passed to the execution, and let `nproc=1`. However, this resulted in 16 "parallel" workers being started on just one physical core.

What I would like to have is executing the command above on one "master" process, which can then spawn jobs on multiple parallel workers. Since I am not familiar with how esm-tools handles the parallel resources, any advice on this would be much appreciated.

**Runscrip and other relevant files**
On branch `feature/cryogrid`
runscript: /esm_tools/runscripts/cryogrid/cryogrid_albedo.yaml
component: /esm_tools/configs/components/cryogrid/cryogrid.yaml

**System (please complete the following information):**
 - Supercomputer: albedo
 - esm-tools version: 6.20.0
 - cryogrid version: 1.0.0

**Comment by mandresm** [comment]
Hi @jannitzbon,

Can you give me permissions to `/albedo/home/jnitzbon/git/esm_tools/cryogrid-1.0.0/run_CGLite_esmtools.sh` so that I can understand what's going on?

**Comment by jannitzbon** [comment]
Sure, but which permissions do you need? I think you should have read access already? 
`-rwxr-xr-x  1 jnitzbon pots   495 Mar 22 12:20 run_CGLite_esmtools.sh`
Anyway, the script `run_CGLite_esmtools.sh` just contains two lines:
```
#!/bin/bash
julia --project=. --threads=1 -p $1 CGLite.jl --forcing-file forcing_for_cryogrid.nc --input-file para_for_cryogrid.nc
```

**Comment by mandresm** [comment]
So you would want to call `run_CGLite_esmtools.sh 16` to run Julia with 16 processes correct?

After reading a bit about Julia in HPCs I think that what we want is to have an sbatch script (`<exp_path>/run_<DATE>/scripts/<expid>_<model>_compute_<DATE>.run`) that in a broader sense makes the following:

```shell
# SBATCH --ntasks=16

module loads <modules>

export <vars>

./run_CGLite_esmtools.sh 16
```

One could even substitute the last line with the following to keep things less convoluted: `julia --project=. --threads=1 -p 16 CGLite.jl --forcing-file forcing_for_cryogrid.nc --input-file para_for_cryogrid.nc`.

For that purpose please consider first this information:
1. `nproc` in ESM-Tools defines broadly speaking the `#SBATCH --ntasks=` defined for SLURM. If you want you can gain further control defining different SLRUM flags, but for this case I don't think it's necessary. So `nproc` should be 16 (you can get rid of the `nproc_julia`).

2. ESM-Tools by defaults creates a `hostfile_srun` file that then it is launch via the `--multi-prog` flag with `srun`. I think this is the main problem, we don't want that. To avoid this you need to modify the `execution_command` in the `computer` section. As this is a standalone model, one can do this via `environment_changes`. You can achieve all of that by adding the following to `/esm_tools/configs/components/cryogrid/cryogrid.yaml`:

```yaml
environment_changes:
    execution_command: "julia --project=. --threads=1 -p ${cryogrid.nproc} CGLite.jl --forcing-file forcing_for_cryogrid.nc --input-file para_for_cryogrid.nc"
```

This would override the default of the `srun` command. Let me know if that works for you or if I am understanding incorrectly how one submits a `Julia` script in Slurm.

**Comment by mandresm** [comment]
Something that it's very important: every variable that is invoked from the `environment_changes` should also specify the section where this variable is taken from. The example here is when we invoke `nproc` within `environment_changes` we preceed it with `cryogrid.`. If we wouldn't do that the parser would try to find `computer.nproc` because the environment changes section is by default `computer`. So let's say you would want to define the path to your forcing file in the yaml file, then you can do the following:

```yaml


environment_changes:
    execution_command: "julia --project=. --threads=1 -p ${cryogrid.nproc} CGLite.jl --forcing-file ${cryogrid.forcing_in_work.ini_forcing} --input-file para_for_cryogrid.nc"
```

**Comment by jannitzbon** [comment]
Thank you so much @mandresm ! The proposed solution is working swiftly.

Short follow-up question: In order to choose the execution command based on whether it is a restart run or not, I tried the following:
```
environment_changes:
    choose_general.lresume:
        1: 
            execution_command: "julia --project=. --threads=1 -p ${cryogrid.nproc} CGLite.jl --forcing-file forcing.nc  --input-file para.nc"
        0: 
            execution_command: "julia --project=. --threads=1 -p ${cryogrid.nproc} CGLite.jl --forcing-file forcing.nc  --input-file restart.nc -r"
```
However, esm_runscript is complaning that `general.lresume` is not defined. I also tried with `cryogrid.lresume` but it did not work either. Is `lresume` special in some respect? Or is there an alternative suggested way to discern restart vs fresh start runs?

**Comment by jannitzbon** [comment]
I solved this using this workaround:

```
choose_lresume:
    0:
        add_environment_changes: 
            execution_command: "julia --project=. --threads=1 -p ${cryogrid.nproc} CGLite.jl --forcing-file forcing.cglite.${start_date!syear}.nc --input-file para.cglite.nc"
    1:
        add_environment_changes:
            execution_command: "julia --project=. --threads=1 -p ${cryogrid.nproc} CGLite.jl --forcing-file forcing.cglite.${start_date!syear}.nc --input-file restart.cglite.nc -r"
```

**Comment by mandresm** [comment]
That is a possibility. The best practice would be though, to declare a variable in outside of the environment with the choose and then call it from the environment. In this way you'll prevent conflicts as you would probably include more chooses in the file in the future for modifying tyhe execution command:

```yaml
choose_lresume:
    0:
        restart_options: --input-file para.cglite.nc
    1:
        restart_options: --input-file restart.cglite.nc -r

environment_changes:
    execution_command: "julia --project=. --threads=1 -p ${cryogrid.nproc} CGLite.jl --forcing-file ${cryogrid.forcing_in_work.ini_forcing} ${cryogrid.restart_options}"
```
