### DISCUSSION TITLE
FESOM restarts with a different time step

### DISCUSSION THREAD

**Discussion by mandresm** [esm-tools/esm_tools#953] [Models] [answered]
Email from @a270067

> just one more question. I wanted to change FESOM time step by continuing an experiment (i.e. run_number > 1). But got an error:
>
>   0:  raw restart time    5097360.00000000      does not match current clock time   5097200.00000000
>   0: 1
> srun: error: l20400: task 0: Exited with exit code 1
>
> Is there any solution?

**Comment by mandresm** [comment, marked as answer]
Hi @a270067,

The way the `fesom-2.0.yaml` is configured is to write a `clock.file` where the previous date is calculated by subtracting the current time step to the current date:

https://github.com/esm-tools/esm_tools/blob/279c277dcad608fdbcaab0fb82af0363f0886f31/configs/components/fesom/fesom-2.0.yaml#L305

and:

https://github.com/esm-tools/esm_tools/blob/279c277dcad608fdbcaab0fb82af0363f0886f31/configs/components/fesom/fesom-2.0.yaml#L322-L325

You could manually define in your runscript `lasttime: "$(( 86400 - <length_of_previous_time_step> ))"` but that would mean that for subsequent legs then you'll get a similar errors for the same reason. Therefore, I suggest you to use a switch (`choose_`) in your runscript so that this change only occurs for the first leg of your restarted simulation:

```yaml
fesom:
    choose_general.run_number:
        <the_run_number_of_the_first_manual_restart>:
            lasttime: "$(( 86400 - <length_of_previous_time_step> ))"
```

Please, let me know if that does the job.
