### ISSUE TITLE
Catch when users does add_namelist_changes without giving namelist section

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1001]
A few weeks ago I had a case where I made an operator error in namelist changes. I did:

```
    add_namelist_changes:
        fort.4:
            LHVOLCA: false
            LCMIP6: true
            NAERANT_SCALE: 0
            CMIP6DATADIR: '/work/ab0246/a270092/input/oifs-43r3/cmip6-data/'
            NCMIPFIXYR: 1850
            SSPNAME: 'historical'
```

instead of
```
    add_namelist_changes:
        fort.4:
            NAERAD:
                LHVOLCA: false
                LCMIP6: true
                NAERANT_SCALE: 0
                CMIP6DATADIR: '/work/ab0246/a270092/input/oifs-43r3/cmip6-data/'
                NCMIPFIXYR: 1850
                SSPNAME: 'historical'
```

I got a cryptic python error message about fitting a boolean into a float or so. Today @Mccino had a similar error. In both cases I only caught it with breakpoints in namelists.py and looking at the specific namelist change that crashes the code.

I think we should have a check in place that verifies the number of levels in a namelist change. I.e. that ensures, that for a namelist change we had 1) the namelist, 2) the section, and 3) the variable.

If we don't have three levels, we should crash and give a clear message saying, the namelist change in line x does not follow FORTRAN syntax.
