### ISSUE TITLE
namelist_changes not working correctly if namelist section does not exist in template

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#1043]
**Describe the bug**
If you try to modify a namelist template from `namelists/echam/....` a (tested with echam and icon)
```yaml
echam:
   namelist_changes:
       namelist.echam:
          testsection:
             show_up: 'you stupid bastard'
```
and the namelist section `testsection` does NOT exist in the template, the resulting namelist in the work directory will only contain
```
&testsection
/
```
but not 
```
&testsection
   show_up = 'you stupid bastard'
/
```
as you would expect. However if the namelist template contains the section (even if it is empty):
```
&testsection
/
```
`namelist_changes` works as always.
**To Reproduce**
See above, any model component should do

**Expected behavior**
Well, add the namelist section and the variable correctly

**System (please complete the following information):**
Tested on levante with a 6.21.19 but I think this is system independent.

**Additional context**
Maybe you fixed this between 6.21 and 6.24 and I missed it. If that's the case I owe you a beer, since well-behaved users regularly update their esm tools installation. :-)
