### ISSUE TITLE
restart files linking instead of copying 

### ISSUE THREAD

**Issue by a270067** [esm-tools/esm_tools#1074]
By high resolution FESOM copying restart files by the end of the job to the next ./run*/work/ takes very long time. In my case up to 40 minutes.
Maybe it make sense to link them via 'ln -s'?

**Comment by JanStreffing** [comment]
You can control the copy/move/link behavior yourself by overwriting the file movements for fesom:

```
file_movements:
        fesom_raw_restart_in:
                all_directions: move
        fesom_raw_restart_out:
                all_directions: move
        fesom_raw_restart_info_in:
                all_directions: move
        fesom_raw_restart_info_out:
                all_directions: move
        fesom_bin_restart_in:
                all_directions: move
        fesom_bin_restart_out:
                all_directions: move
        fesom_bin_restart_info_in:
                all_directions: move
        fesom_bin_restart_info_out:
                all_directions: move
```

I think the binary ones you should not link, since they would be overwritten with the same name in place. This is not save. The netcdf parallel restarts you can potentially link, if you are willing to accept the risk that fesom will add new timesteps in case the run is restarted more than once per year.
