### ISSUE TITLE
compile flags for FESOM

### ISSUE THREAD

**Issue by tsemmler05** [esm-tools/esm_tools#1080]
Similarly to oifs.env.yaml, I would like to define FESOM_FFLAGS, i.e. specific fortran compile flags for FESOM2 on a specific machine, in my case ecmwf-atos.

To achieve this, I added to fesom-2.0.yaml (under configs/fesom):

+compiletime_environment_changes:
+  choose_computer.name:
+    ecmwf-atos:
+      FESOM_FFLAGS: '"-r8 -i4 -fp-model precise -no-prec-div -no-prec-sqrt -fimf-use-svml -xHost -ip -init=zero -no-warp-margin -march=core-avx2 -mtune=core-avx2"'

However, this change does not lead to any difference in my executable. I also tried to replace FESOM_FFLAGS with FESOM2_FFLAGS, without success.

Do I have to do anything in addition to make sure that this change is picked up?

I am running esm-tools version 6.22.0

Thanks in advance for your advice.

**Comment by nwieters** [comment]
Hi @tsemmler05,
can you give a path to the changed fesom-2.0.yaml file please? Then I can have a look tomorrow.
Thank you.

**Comment by nwieters** [comment]
Hi @tsemmler05,
are you running FESOM2 standalone?

**Comment by nwieters** [comment]
Hi @tsemmler05,

I tried to add these compile flags to FESOM2 in AWICM3.1 on Albedo. This works for me:

Add the following lines in the fesom block in `configs/setups/awicm3/awicm3.yaml`

```
compiletime_environment_changes:
    choose_computer.name:
        ecmwf-atos:
            add_export_vars:
                - 'FFLAGS="-r8 -i4 -fp-model precise -no-prec-div -no-prec-sqrt -fimf-use-svml -xHost -ip -init=zero -no-warp-margin -march=core-avx2 -mtune=core-avx2"'
```

To check if this flags were applied, check if they are in the `CMakeChache.txt` file in the `build` folder of `fesom.2.0`.

Let me know, if this works also for you on ecmwf-atos.
