### ISSUE TITLE
further_reading with esm_master

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1085]
For the new oifs48r1 I want a separate oifs.env.yaml, which I called oifs48.env.yaml
At first I tried to place the different further reading blocks into the compile_infos like so:
```
compile_infos:
        choose_version:
          48r1:
            branch: main
            comp_command: "./openifs-bundle build --threads=32 --arch=esm_tools --openifs-only --without-double-precision --install; chmod -R ${source_code_permissions} .; mv install/bin/ifsMASTER.SP install/bin/oifs"
            clean_command: ./openifs-bundle build --clean
            git-repository: https://gitlab.dkrz.de/ec-earth/oifs-48r1.git
            install_bins: install/bin/oifs
            destination: oifs-48r1
            further_reading:
              - oifs/oifs48.env.yaml
```
Since this did not seem to do anything I instead placed it in the version choose block:
```
choose_version:
        48r1:
                further_reading:
                        - oifs/oifs48.env.yaml
```
Again no luck.
I'm trying to get these variables into the compile script:

```
# Setup up compile and runtime environment i.e. what needs
# to be changed w.r.t the default config/machines/<computer>.yaml
compiletime_environment_changes:
  choose_computer.name:
    juwels:
      add_export_vars:
        - OIFS_CYCLE: 48r1
        - OIFS_HOME: "${model_dir}"
        - OIFS_LOGFILE: "$OIFS_HOME/oifs_test_log.txt"
        - OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"

environment_changes:
  OpenMP_flag: ""
  OpenMP_CCDEFS: ""
```

You can find my attempts at:
https://github.com/esm-tools/esm_tools/tree/oifs48r1

**Comment by nwieters** [comment]
Hi @JanStreffing,

I am not sure if this solves the problem. But I found that the entries in `add_export_vars` for juwels (in e.g. `configs/components/oifs/oifs.env.yaml`) are placed between ''.

```
compiletime_environment_changes:
  choose_computer.name:
    juwels:
      add_export_vars:
        - 'OIFS_CYCLE: 48r1'
        - 'OIFS_HOME: "${model_dir}"'
        - 'OIFS_LOGFILE: "$OIFS_HOME/oifs_test_log.txt"'
        - 'OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"'

```

**Comment by mandresm** [comment]
HI @JanStreffing,

There is a syntax problem in your `add_export_vars`, you are mixing the dictionary syntax and the list syntax. As you have it ESM-Tools will write the following in the bash scripts:

```bash
export OIFS_CYCLE: 48r1
export OIFS_HOME: "<dir_to_awicm3>"
export OIFS_LOGFILE: "$OIFS_HOME/oifs_test_log.txt"
export OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"
```

Please, for anything that is new use the dictionary syntax for the `export_vars`:

```yaml
compiletime_environment_changes:
  choose_computer.name:
    juwels:
      add_export_vars:
        OIFS_CYCLE: 48r1
        OIFS_HOME: "${model_dir}"
        OIFS_LOGFILE: "$OIFS_HOME/oifs_test_log.txt"
        OIFS_DATA_DIR: "/p/project/chhb19/streffing1/input/oifs-48r1/"
```
