### ISSUE TITLE
iolibraries switch does not work from within choose_version block

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1123]
I recently stumbled over this behaviour. While doing test compiles of oasis as a standalone component on juwels, I needed to set iolibraries. Normally I never run standalone models that are not oifs and iolibraries is set in oifs.env.yaml.

Now I wanted to put a default iolibraries just for the new oasis version, like so:

```
choose_version:
  6.0-YAC:
    environment_changes:
      choose_computer.name:
        juwels:
          iolibraries_name: awi_libs
```
This is ignored. With Miguel, I found that it works like this:
```
environment_changes:
  choose_computer.name:
    juwels:
      iolibraries_name: awi_libs
```
But of course this would have defaults for older oasis versions. Not ideal. This also doesn't work:
```
choose_version:
  6.0-YAC:
    choose_computer.name:
      juwels:
        iolibraries_name: awi_libs
compiletime_environment_changes:
  iolibraries: ${iolibraries_name}
```
