### ISSUE TITLE
Functionality to change component variables from setups in esm_master (part 2)

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1221]
I found recently, that on release I can not overwrite a comp_command that is given in a choose block in the component, with another comp command that is given in a choose block in a setup. This seems related to: #32 

For FESOM we did a workaround by using the default command in the component, thereby allowing the setup comp command to overwrite.

For OpenIFS 48r1 I do not see how to make this work. 43r3 and 48r1 have too different comp commands in the component to use a single default.

**Comment by mandresm** [comment]
Can you give me an example on how can I reproduce exactly this behavior?

**Comment by mandresm** [comment]
I know we went over this, but I have forgotten. If it's written here I can at any time just jump in, reproduce it and try to fix it

**Comment by mandresm** [comment]
from @JanStreffing:

Branch: `feat/awicm3-v3.3_new`
Commit-id: `488db2790113e60a34fab5def5d5d45e61dcb6ce`
Steps to reproduce: `esm_master comp-awicm3-v3.3/oifs -c`

The `comp_command` should differ from what is defined in `oifs-48r1` commented lines. "without commenting out the comp_command from the oifs.yaml, the one from awicm3.yaml is not used"

**Comment by mandresm** [comment]
A provisional solution:

What about having the following?

oifs.yaml

```yaml
    48r1:
        comp_command: "./openifs-bundle create; ./openifs-bundle build --threads=32 --openifs-only --without-single-precision ${comp_options} --install"

comp_options: "" 
```
And then in awicm3.yaml

```yaml
    v3.3:
        comp_options: "--with-cplng2 --with-oifs-xios" 
```
