### ISSUE TITLE
Help with variables.

### ISSUE THREAD

**Issue by hajlaci** [esm-tools/esm_tools#1249]
Could you help me with this:

```
mygrid: T159
        install_bins: build/guess_T159
        #install_bins: build/guess_${mygrid}
        executable: guess

        environment_changes:
            add_add_add_add_add_export_vars:
                myfortrancompiler: $FC
                mygrid: T159
                #mygrid: ${mygrid}
```

I would like to use the "mygrid" variable in different parts of the yaml file. Can you help me with how to reference it. The commented parts are how I tried.

**Comment by mandresm** [comment]
In general, what you were doing was correct. However, anything you put inside `environment_changes` goes to the `computer` scope, and there `${mygrid}` is not available right away.

Instead, try writing: 

```yaml
        environment_changes:
            add_add_add_add_add_export_vars:
                myfortrancompiler: $FC
                mygrid: ${lpj_guess.mygrid}
```
