### ISSUE TITLE
coupling fields defined in components 

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#127]
One question on my way to an awicm3 setup:
Currently coupling fields are currently defined in the component yamls. Wouldn't the couplings yamls be a better location? When coupling fesom-2.0 to oifs I use different fields than coupling fesom-2.0 into to echam. When coupling oifs to fesom-2.0 I use different fields and grids than when it's coupled to nemo.

In the basic oifs.yaml for example I find this block containing foci information:

```
foci_fields_a: [A_QsrMix, A_QnsMix, ATotRain]
foci_fields_l: [AIceFrac, A_SSTSST, A_TepIce, A_IceTck, A_SnwTck, A_OCurx1, A_OCury1, A_OTaux1, A_OTauy1, A_ITaux1, A_ITauy1, A_QsrIce, A_QnsIce, ATotSnow, AIceEvap, A_dQnsdT]
foci_fields_r: [A_Runoff]

coupling_fields:
        "[[foci_fields_a-->FIELD]]":
                grid: atma
        "[[foci_fields_l-->FIELD]]":
                grid: atml
        "[[foci_fields_r-->FIELD]]":
                grid: atmr

# A grid at N80 resolution is A080 etc.
grids:
        atma:
                name: ${oasis_grid_name_a}
                nx: "${nx}"
                ny: "${ny}"
                oasis_grid_type: "D"
        atml:
                name: ${oasis_grid_name_l}
                nx: "${nx}"
                ny: "${ny}"
                oasis_grid_type: "D"
        atmr:
                name: ${oasis_grid_name_r}
                nx: "${nx}"
                ny: "${ny}"
                oasis_grid_type: "D"
```

My grids have different names (following EC-Earth nameing convention) and coupling_fields are not just renamed but also contain different fields. I would have to double up this code section and the coupling_fields: part I would need to replace/overwrite elsewhere. It would feels clunky to have a default coupling that have to overwrite elsewhere later.

For the fesom.yaml I would need to add:

```
coupling_fields:
        sia_feom:
                grid: feom
        ist_feom:
                grid: feom
```

A related question is: Do I need to use all fields defined here for any given coupling, or is this a selection of everything that is available?

If I have overlooked something some smart solution, let me know ;-)
