### ISSUE TITLE
Oasis different dt for different couplings

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1278]
Currently, we have only one oasis `time_step` that is applied for all couplings. For AWI-ESM3 we need daily coupling (86400s) for OpenIFS-LPJG, while the OpenIFS-FESOM2 coupling should stay at 1h (3600s). Is this already a feature, or something that needs to be developed? If so, any pointers how? Changes needed only to oasis.py, or elsewhere?

Also adding @hajlaci

**Comment by mandresm** [comment]
This needs to be develop. The place where I would put it would be in `oasis.py`, here:

https://github.com/esm-tools/esm_tools/blob/66e23a5f9670a6781837f134c49d980e5d61c512/src/esm_runscripts/oasis.py#L77-L124

Right bellow:

```diff
     seq = int(direction.get("seq", "2")) 
     # if transformation.get("postprocessing", {}).get("conserv", {}).get("method"): 
     #    seq += 1 

+    coupling_time_step = direction.get("coupling_time_step", coupling_time_step)
```

This would allow you to add a coupling time step to a given direction:

```yaml
            # Default
            coupling_time_step: 3600
            land_atmo_coupling_time_step: 86400

            coupling_directions:
                'atma->feom':
                        lag: ${a2o_lag}
                        seq: ${a2o_seq}
                'atmr->rnfa':
                        lag: ${r2a_lag}
                        seq: ${r2a_seq}
                'rnfo->feom':
                        lag: ${o2r_lag}
                        seq: ${o2r_seq}
                'feom->atma':
                        lag: ${o2a_lag}
                        seq: ${o2a_seq}
                'lpjg->atma':
                        lag: ${v2a_lag}
                        seq: ${v2a_seq}
                        coupling_time_step: ${land_atmo_coupling_time_step}
                'atma->lpjg':
                        lag: ${a2v_lag}
                        seq: ${a2v_seq}
                        coupling_time_step: ${land_atmo_coupling_time_step}
```
