### ISSUE TITLE
LPJ-GUESS Directory Setup in ESM-Tools

### ISSUE THREAD

**Issue by hajlaci** [esm-tools/esm_tools#1279]
Hi Miguel,

We’ve discovered that LPJ-GUESS requires a unique directory for each processor it runs on, named in the format run<processor_number>. Additionally, these directories must contain copies of all the forcing files. This setup is currently handled during the precompilation stage using a script engine.

We need to reproduce this process within esm_tools and would greatly appreciate your help in getting this done.

Cheers,
Laszlo

**Comment by mandresm** [comment]
Hi @hajlaci,

That is an interesting way of doing things from the LPJ-GUESS side... I have some questions:

- Do these directories need any other files other than copies of the forcings?
- Is the number of processors something that is given during compilation, or the same binary can run with different numbers of processors specified via `lpj_guess.nproc`?

In principle, doing this should not be difficult to do with ESM-Tools. You'll need to use the file dictionaries for the forcing files and expand them with a list loop (https://esm-tools.readthedocs.io/en/latest/yaml.html#list-loops) to generate all the `forcing_in_work` targets for `run<number_of_processors>`, in a similar way you did with the `[[coupling_fields->FIELDS]]`.

There are some examples of how one can do such a thing in the `echam.yaml`:

https://github.com/esm-tools/esm_tools/blob/66e23a5f9670a6781837f134c49d980e5d61c512/configs/components/echam/echam.yaml#L813-L838

Something on these lines (metacode, not really tested):

```yaml
lpj_guess:
    # Make a list of processor numbers
    proc_list: $(( list(range($nproc)) )) # if the first proc number needs to be 0 or $(( list(range(1, $nproc+1)) )) if the first proc number needs to be 1

     forcing_sources: 
         "my_forcing_label_[[proc_list-->PROC_NUM]]": /path/to/forcing/file

    forcing_in_work:
         "my_forcing_label_[[proc_list-->PROC_NUM]]": runPROC_NUM/file
```

Please, let me know if I am understanding the problem correctly and answer the questions I asked at the beginning. If I am understandind the problem correctly, I would recommend that you try this suggestion. If you get stuck, commit and write down here the commit_id and the branch and I'll have a look at it. I am not reachable tomorrow and on Friday and on Monday and Tuesday I'm on a retreat, so responding to this thread is actually the fastest way of getting a response from me (cause I'll be paying attention to GitHub :) )

**Comment by hajlaci** [comment]
Hi @mandresm,

Thank you so much for your suggestions! I’ll give them a try.

To answer your questions:
It’s a bit more complex because, within the directories created for each processor, we also need several subdirectories, such as output and fire. Additionally, we need to copy most of the forcing and restart files (if any exist) into those directories.

Essentially, we need to replicate the structure outlined in the attached .yaml file used in esm_tools. It might make more sense to you than it does to me.
[pre-lpjg.txt](https://github.com/user-attachments/files/18516858/pre-lpjg.txt)

As for the number of processors: it’s not set during compilation but rather at runtime. This is defined in the main run script:

...
`
lpj_guess:
    resolution: "TL159"
    lresume: false
    nproc: 128
    omp_num_threads: 1 
`
....

Cheers, 
L

**Comment by mandresm** [comment]
>  It’s a bit more complex because, within the directories created for each processor, we also need several subdirectories, such as output and fire. 

That should be no problem, ESM-Tools can create nested directories in the `_in_work` files.

> Additionally, we need to copy most of the forcing and restart files (if any exist) into those directories.

That will be done for you if you use the approach above. I would suggest that you actually link as many of those files as possible, to reduce data duplication. I would suggest, first try copying and when all is looking good, I can help you with the linking.

> Essentially, we need to replicate the structure outlined in the attached .yaml file used in esm_tools. It might make more sense to you than it does to me.
[pre-lpjg.txt](https://github.com/user-attachments/files/18516858/pre-lpjg.txt)

Okay, thanks for sharing that. Just a comment, in general is much more easy if you copy paste code or file contents in GitHub using code snippets, but for now this file does the job :) (https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks). If you use code snippets, then you code snippet would look like:

```yaml
- base.echo:
     msg: "{{experiment.schedule.start}}"
- base.echo:
     msg: "{{experiment.src_dir}}"
- base.echo:
#      msg: "{{experiment.base_dir}}"
     msg: "{{experiment.run_dir}}"
- base.echo:
     msg: "Grid: {{model_config.oifs.grid.hres}}"
#comment in:
- base.template:
     src: "namelist.lpjg.j2"
     dst: "lpjg_steps.rc"
##Control files (i.e. .ins, landuse, N deposition, soil type files etc.)
#copy co2:
- base.copy:
   src: "/proj/rescue/optimesm/run/OPr5/mole_fraction_of_carbon_dioxide_in_air_input4MIPs_lpjg.nc"
   dst: "{{experiment.run_dir}}"
- base.copy: 
   src: "{{experiment.src_dir}}/LPJ-GUESS-lpjg_v4p1/data/ins/*"
   dst: "{{experiment.run_dir}}"
# Copy slt_{GRID}.nc:
- base.copy:
   src: "{{experiment.lpjg_ini_dir}}/lpjg/slt_{{model_config.oifs.grid.hres}}.nc"
   dst: "{{experiment.run_dir}}"     
# Copy vegin:  "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/vegin.nc"
- base.copy:
   src: "/home/rossby/ece-3-inidata/lpjg/oasismct/vegin.nc"
   dst: "{{experiment.run_dir}}"
- base.make_dir:
       path: "{{experiment.run_dir}}/landuse"
- base.make_dir:
       path: "{{experiment.run_dir}}/fire"
- base.echo:
   msg: "{{experiment.schedule.start}}"
- base.echo:
   msg: "{{experiment.schedule.leg.start}}"
#1588-1619:
#for (( n=1; n<=${lpjg_numproc}; n++ ))
#set lpjg_numproc_=10, this is set in slurm??"
- base.context:
    job:
      lpjg:
        ntasks: "{{experiment.lpjg.numproc}}" 
         
#
#    mylist: [1,2,3,4,5,6,7,8,9,10]
    mylist: {{range(experiment.lpjg.num_proc) |list}}
- base.echo:
    msg: "ULUND - show list: {{mylist}}"
- base.echo:
    msg: "check lpjg.restart etc: "
- base.echo:
    msg: "{{experiment.lpjg.restart}}"
- base.echo:
    msg: "{{'{{experiment.run_dir}}/run{{item}}' | exists}}"
- base.context:
   doesdir_exist : "{{'{{experiment.run_dir}}/run{{item}}' | exists}}"
- do:
#iterate over processes:
#if ! $leg_is_restart || [ ! -d ${run_dir}/run${n} ]
  - when: "not {{experiment.lpjg.restart}} or  not {{doesdir_exist}}"
#  - when: "{{1==1}}"
    do: 
#lpjgine 1591-1606:
           - base.make_dir:
                 path: "{{experiment.run_dir}}/run{{item}}/output"
           - base.copy:
                 src:  "{{experiment.run_dir}}/*.ins"
                 dst:  "{{experiment.run_dir}}/run{{item}}"
                 ignore_not_found: true
#copy output control files:
           - base.copy:
                  src: "{{experiment.lpjg.lpjg_outctrl}}/lpjg_cmip6_output.ins"
                  dst: "{{experiment.run_dir}}/run{{item}}"
                  ignore_not_found: true
           - base.link: 
                  target: "{{experiment.lpjg.lpjg_outctrl}}/lpjg_cmip6_output.ins"
                  link:   "{{experiment.run_dir}}/run{{item}}/lpjg_cmip6_output.ins.lnk"
           - base.copy:
                   src: "/proj/rescue/optimesm/run/OPr5/run11/ghg*.txt"
                   dst: "{{experiment.run_dir}}/run{{item}}"
                   ignore_not_found: true
           - base.copy:
                   src: "{{experiment.lpjg_ini_dir}}/lpjg/ece_gridlist_{{model_config.oifs.grid.hres}}.txt"
                   dst: "{{experiment.run_dir}}/run{{item}}/ece_gridlist.txt"
                   ignore_not_found: true
           - base.link:
                   target: "{{experiment.lpjg_ini_dir}}/lpjg/ece_gridlist_{{model_config.oifs.grid.hres}}.txt"
                   link:   "{{experiment.run_dir}}/run{{item}}/ece_gridlist.txt.lnk"
# Copy slt_{GRID}.nc:
           - base.copy:
                   src: "{{experiment.lpjg_ini_dir}}/lpjg/slt_{{model_config.oifs.grid.hres}}.nc"
                   dst: "{{experiment.run_dir}}/run{{item}}"
                   ignore_not_found: true             
           - base.link:
                   target: "{{experiment.lpjg_ini_dir}}/lpjg/slt_{{model_config.oifs.grid.hres}}.nc"
                   link:   "{{experiment.run_dir}}/run{{item}}/slt_{{model_config.oifs.grid.hres}}.nc.lnk"
           - base.copy:
                   src: "/home/rossby/ece-3-inidata/lpjg/oasismct/vegin.nc"
                   dst: "{{experiment.run_dir}}/run{{item}}"
                   ignore_not_found: true

## Data only needed by master
           - when: "{{iter == 1 }}"
             do:
                - base.echo:
                     msg: "item::: {{item}}"
                - base.make_dir:
                     path: "{{experiment.run_dir}}/run{{item}}"
                - base.echo:
                     msg: "job.lpjg.ntasks: {{job.lpjg.ntasks}}"
                - base.make_dir:
                     path: "{{experiment.run_dir}}/run{{item}}"
                - base.copy:
                     src: "{{experiment.run_dir}}/*.ins"
                     dst: "{{experiment.run_dir}}/run{{item}}"
                - base.copy:
                     src: "{{experiment.run_dir}}/outputcontrol/lpjg_cmip6_output.ins"
                     dst: "{{experiment.run_dir}}/run{{item}}"
                     ignore_not_found: true
                - base.link:
                     target: "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/{{model_config.oifs.grid.hres}}/ece_gridlist_{{model_config.oifs.grid.hres}}.txt"
                     link: "{{experiment.run_dir}}/run{{item}}/ece_gridlist.txt.lnk"
                - base.echo:
                     msg: "About to do when: item ==1"
                - when: "{{item == 1}}"
                  do:
                         - base.echo:
                              msg: "ULUND1: loop when item==1"
                         - base.copy:
                              src: "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/{{model_config.oifs.grid.hres}}/*.nc"
                              dst: "{{experiment.run_dir}}"
                              ignore_not_found: true
                         - base.copy:
                              src: "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/lpjgv.txt"
                              dst: "{{experiment.run_dir}}/run{{item}}"
                              ignore_not_found: true
                                # Will need the next lines for restarts:
                                #- base.remove:
                                #path: "{{experiment.run_dir}}/lpjgv.nc"
                                #- base.remove:
                                #path: "{{experiment.run_dir}}/vegin.nc"
                         - base.copy:
                                #src: "/home/rossby/ece-3-inidata/lpjg/oasismct/lpjgv.nc"
                                # src: "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/lpjgv.nc"
                                src: "/proj/rescue/ece-4-inidata/lpjg/oasismct/lpjgv_ece4.nc"
                                dst: "{{experiment.run_dir}}"
                                #ignore_not_found: false
                         - base.copy:
                              src: "/home/rossby/ece-3-inidata/lpjg/oasismct/vegin.nc"
                                #src:  "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/vegin.nc"
                              dst:  "{{experiment.run_dir}}"
                                #ignore_not_found: false
                         - base.copy:
                              #src: "/home/rossby/ece-3-inidata/lpjg/oasismct/lpjgv.nc"  
                              #src: "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/lpjgv.nc"
                              src: "/proj/rescue/ece-4-inidata/lpjg/oasismct/lpjgv_ece4.nc"
                              dst: "{{experiment.run_dir}}/run{{item}}"
                                #ignore_not_found: false
                         - base.copy:
                              src: "/home/rossby/ece-3-inidata/lpjg/oasismct/vegin.nc" 
                           #src:  "{{experiment.lpjg_ini_dir}}/lpjg/oasismct/vegin.nc"
                              dst:  "{{experiment.run_dir}}/run{{item}}"
                                #ignore_not_found: false
                         - base.make_dir:
                              path: "{{experiment.run_dir}}/run{{item}}" 
  loop: "{{mylist}}"

- base.context:
   job:
     guess: "./guess_{{model_config.oifs.grid.hres}} guess.ins -parallel"
- base.echo:
     msg: "job.guess: {{job.guess}}"
```

> As for the number of processors: it’s not set during compilation but rather at runtime. This is defined in the main run script:

That is good news.

In summary, all your requirements are possible to fulfill with what I suggested, if you get stuck, just commit, push, and I'll have a look on the same day :)
