### ISSUE TITLE
useMPI vs compiler_suite vs compiler_mpi

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#1297]
In different machine files, we use these three switches:

- useMPI
- compiler_suite
- compiler_mpi

They do similar, sometimes identical things. This results in strange choose blocks like:

```
  "2.5":
    git-repository: https://gitlab.dkrz.de/ec-earth/xios-2.5.git
    archfile: ESMTOOLS_generic_oasis_intel
    choose_computer.useMPI: # JS: This entire block is a missnomer. It's not the MPI thats imporant but the compiler cray ftn vs intel.
      cray_mpich:
        archfile: ESMTOOLS_generic_oasis_cray
      intelmpi:
        archfile: ESMTOOLS_generic_oasis_intel
      parastationmpi:
        archfile: ESMTOOLS_generic_oasis_intel
      "*":
        foo: bar
    # MA: yet another block, this time for albedo. We cannot fix this now, but in the
    # future we should adopt the compiler suite logic for the other computers. Already
    # included in ESM-Tools clickup
    choose_computer.compiler_suite:
        gcc:
            archfile: ESMTOOLS_generic_oasis_gcc
        intel-oneapi:
            archfile: ESMTOOLS_levante_oasis_intel
        "*":
            foo: bar
    # JS: On levante this switch has yet another name. Again only the compiler part matters.
    choose_computer.name:
        levante:
            choose_computer.compiler_mpi:
                gnu11_ompi4:
                    archfile: ESMTOOLS_generic_oasis_gcc
                "*":
                    archfile: ESMTOOLS_levante_oasis_intel
        juwels:
            choose_computer.compiler_mpi:
                gnu2023_ompi2023:
                    archfile: ESMTOOLS_generic_oasis_gcc
                "*":
                    archfile: ESMTOOLS_levante_oasis_intel
```

I have a dream...
I dont want these to be called different names... Some day.
