### ISSUE TITLE
Iterative coupling not working due to failing esm-tools-plugins/esm_pism installation

### ISSUE THREAD

**Issue by jannitzbon** [esm-tools/esm_tools#1337]
**Describe the bug**
I want to use the workflow manager to set up an iteratively coupled run between awiesm-2.6 and cryogrid (a permafrost model). This has worked in the past with awiesm-2.1 and cryogrid. However, when I start the runscript I get the following error:

> $ esm_runscripts runscript_awiesm-cryogrid_coupled.yaml -e PCMIP_PIctrl_CGLite_test -c
Initializing iterative coupling
WARNING: Ignoring invalid distribution -ip (/albedo/soft/sw/spack-sw/python/3.10.4-daos5pe/lib/python3.10/site-packages)
Collecting https://github.com/esm-tools-plugins/esm_pism
  Downloading https://github.com/esm-tools-plugins/esm_pism
     - 252.0 kB 4.5 MB/s 0:00:00
  ERROR: Cannot unpack file /tmp/pip-unpack-qmp1otpj/esm_pism (downloaded from /tmp/pip-req-build-ei5yiejn, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-ei5yiejn
WARNING: Ignoring invalid distribution -ip (/albedo/soft/sw/spack-sw/python/3.10.4-daos5pe/lib/python3.10/site-packages)
Collecting https://github.com/esm-tools-plugins/esm_pism
  Using cached https://github.com/esm-tools-plugins/esm_pism
  ERROR: Cannot unpack file /tmp/pip-unpack-uggvs50r/esm_pism (downloaded from /tmp/pip-req-build-kd9pb42y, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /tmp/pip-req-build-kd9pb42y
Traceback (most recent call last):
  File "/albedo/home/jnitzbon/git/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 224, in install
    subprocess.check_call(arg_list)
  File "/albedo/soft/sw/spack-sw/python/3.10.4-daos5pe/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/albedo/soft/sw/spack-sw/python/3.10.4-daos5pe/bin/python3.10', '-m', 'pip', 'install', '--user', 'https://github.com/esm-tools-plugins/esm_pism']' returned non-zero exit status 1.

It seems that the installation of esm_pism fails. **However, I do not know why I should need this plugin in the first place?** I do not intend to use the iterative coupling for PISM. 

**To Reproduce**
The respective runscripts can be found here:
`/albedo/work/projects/paleo_work/jnitzbon/PermafrostCloudMIP/runscripts/awiesm-cryogrid/`

**Expected behavior**
The runs should start without trying to install esm_pism.

**System (please complete the following information):**
 - Supercomputer: albedo
 - Version 6.50.0

**Comment by mandresm** [comment]
@ackerlar, do you know why this plugin is required?

**Comment by mandresm** [comment]
Hi again @jannitzbon,

So the problem is here:

https://github.com/esm-tools/esm_tools/blob/20b744a31f5e7979a73f7038556f9dbec68b42a6/configs/setups/awiesm/awiesm.yaml#L150-L153

That is assuming that iterative coupling for AWIESM always means running with PISM, which is not the case. @ackerlar, you understand better the requirements of running with PISM, any chance you can suggest or make a change to that choose block? We might be able to use as case a variable in general that contains the list of offline coupled models. I'll look into that as well.

For the time been, @jannitzbon, you can comment those lines.

**Comment by ackerlar** [comment]
I guess it would make sense to include a `choose_` block that depends on the 2nd model that is coupled to AWI-ESM. Something like `choose_general.model2.setup_name` (I don't know if the syntax is correct but the idea should be clear)

**Comment by mandresm** [comment]
makes sense, I can make a PR for that. Could you check that that does not break your setup @ackerlar?

**Comment by ackerlar** [comment]
Yes, I am currently trying to run a test run

**Comment by ackerlar** [comment]
```
        choose_general.iterative_coupling:
            True:
                choose_model2.setup_name:
                    "pism":                                                                                                                                      
                        required_plugins:
                            - "https://github.com/esm-tools-plugins/esm_pism"
        
```

Seems to work for me. To include other PISM instances I would prefer something like:

```
        choose_general.iterative_coupling:
            True:
                choose_model2.setup_name:
                    "pism" | "pism_nh" | "pism_sh":                                                                                                                                      
                        required_plugins:
                            - "https://github.com/esm-tools-plugins/esm_pism"
```

Does this make sense?

**Comment by jannitzbon** [comment]
Thanks to both of you for the clarification and fix! 

Maybe you could also help me with a quick follow up question regarding the iterative coupling:
I would like to choose a different JSBACH input file, depending on whether it is the very first year (initial_date) of the iteratively coupled run, or a subsequent run. (Background: the cryogrid output is used to overwrite a variable in the jsbach.nc input file such that the latter one is changing at every coupling step.)  

I tried with an `choose_start_date:` block, but this did not seem to work. 
Then I thought about moving/renaming the initial JSBACH input file following in the same way I treat the subsequent years (`... jsbach_1850: "${general.base_dir}/${general.expid}/couple/jsbach/jsbach.$(( ${start_date!syear} - 1 )).nc"`). But I am not sure if/how this could be done via the runscript.

**Comment by mandresm** [comment]
> I tried with an choose_start_date: block, but this did not seem to work.

That probably did not work because is a date object, and you probably did not match the case. Also, that is not very general as if you change the initial date things will break. I suggest you use `general.run_number` that is basically an index for the leg number. So something like this:

```yaml
jsbach:
    choose_general.run_number:
        1:
            place_holder: "does nothing"
        "*": # This is an else to the choose_ switching logic
            key_to_be_changed: value_to_be_changed
```

**Comment by mandresm** [comment]
@ackerlar, the "or" logic does not exist in the choose_ logic. It could be implemented but it would greatly increase it's complexity. In this cases is probably better to define a variable with a python snippet on it, for example:

```yaml
choose_general.iterative_coupling:
    True:
        with_pism: $(( "pism" in ${model2.setup_name} ))   # Anything inside a $(( )) will be evaluated by python after substitution of the ${variables}
        choose_with_pism:
            True:
                required_plugins:
                    - "https://github.com/esm-tools-plugins/esm_pism"
```

**Comment by ackerlar** [comment]
> > I tried with an choose_start_date: block, but this did not seem to work.
> 
> That probably did not work because is a date object, and you probably did not match the case. Also, that is not very general as if you change the initial date things will break. I suggest you use `general.run_number` that is basically an index for the leg number. So something like this:
> 
> jsbach:
>     choose_general.run_number:
>         1:
>             place_holder: "does nothing"
>         "*": # This is an else to the choose_ switching logic
>             key_to_be_changed: value_to_be_changed




Maybe important to differentiate between `run_number` and `chunk_number` if you run multiple AWI-ESM runs in one chunk. This is how we solved this for PISM:

```
                choose_general.iterative_coupling:
                        True:
                                add_input_sources:
                                        "jsbach_ismc": "${general.experiment_couple_dir}/latest_jsbach_init_file.nc"
                                choose_general.chunk_number:
                                        1:  
                                                from_chunk_number_choose: <NOT_SPECIFIED>
                                        "*":
                                                add_input_files:
                                                        jsbach: jsbach_ismc
                        "*":
                                from_iterative_coupling_choose: <NOT_SPECIFIED> 
```

**Comment by ackerlar** [comment]
> True:
>         with_pism: $(( "pism" in ${model2.setup_name} ))   # Anything inside a $(( )) will be evaluated by python after substitution of the ${variables}
>         choose_with_pism:
>             True:
>                 required_plugins:
>                     - "https://github.com/esm-tools-plugins/esm_pism"


Thanks @mandresm but I get this error when I try it with your solution:

```
Traceback (most recent call last):
  File "/home/a/a270124/.local/bin/esm_runscripts", line 33, in <module>
    sys.exit(load_entry_point('esm-tools', 'console_scripts', 'esm_runscripts')())
  File "/home/a/a270124/esm_tools/src/esm_runscripts/cli.py", line 285, in main
    setup = SimulationSetup(command_line_config=command_line_config)
  File "/home/a/a270124/esm_tools/src/esm_runscripts/sim_objects.py", line 107, in __init__
    self.config = prepare.run_job(self.config)
  File "/home/a/a270124/esm_tools/src/esm_runscripts/prepare.py", line 20, in run_job
    helpers.evaluate(config, "prepare", "prepare_recipe")
  File "/home/a/a270124/esm_tools/src/esm_runscripts/helpers.py", line 71, in evaluate
    config = esm_plugin_manager.work_through_recipe(
  File "/home/a/a270124/esm_tools/src/esm_plugin_manager/esm_plugin_manager.py", line 159, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/home/a/a270124/esm_tools/src/esm_runscripts/prepare.py", line 129, in resolve_some_choose_blocks
    esm_parser.choose_blocks(config, blackdict=config._blackdict)
  File "/home/a/a270124/esm_tools/src/esm_parser/esm_parser.py", line 2707, in choose_blocks
    resolve_basic_choose(
  File "/home/a/a270124/esm_tools/src/esm_parser/esm_parser.py", line 1445, in resolve_basic_choose
    choice = do_math_in_entry([False], choice, config)
  File "/home/a/a270124/esm_tools/src/esm_parser/provenance.py", line 873, in inner
    output = func(tree, rhs, *args, **kwargs)
  File "/home/a/a270124/esm_tools/src/esm_parser/esm_parser.py", line 2433, in do_math_in_entry
    result = eval(math)
  File "<string>", line 1, in <module>
NameError: name 'pism' is not defined
```

**Comment by jannitzbon** [comment]
Hi @ackerlar  @mandresm  thanks for following up on this. After fixing the issue above, I ran into another, similar, issue, as the `fesom-2.6.yaml` config file has also two `choose_iterative_coupling` blocks, which assume an ice sheet coupling. I will comment these out for my use now, but probably a simiar generic solution would be advisable here.

https://github.com/esm-tools/esm_tools/blob/20b744a31f5e7979a73f7038556f9dbec68b42a6/configs/components/fesom/fesom-2.6.yaml#L241

**Comment by mandresm** [comment]
> Thanks [@mandresm](https://github.com/mandresm) but I get this error when I try it with your solution:

I think you forgot the $ before the (()):

```yaml
        with_pism: $(( "pism" in ${model2.setup_name} ))
```

**Comment by ackerlar** [comment]
> > Thanks [@mandresm](https://github.com/mandresm) but I get this error when I try it with your solution:
> 
> I think you forgot the $ before the (()):
> 
>         with_pism: $(( "pism" in ${model2.setup_name} ))


No, this is the code:

```
        choose_general.iterative_coupling:
            True:
                with_pism: $(( "pism" in ${model2.setup_name} ))   # Anything inside a $(( )) will be evaluated by python after substitution of the ${variables}                         
                choose_with_pism:
                    True:
                        required_plugins:
                            - "https://github.com/esm-tools-plugins/esm_pism"
                           
```
