### ISSUE TITLE
Copying LPJ-GUESS restart files

### ISSUE THREAD

**Issue by hajlaci** [esm-tools/esm_tools#1343]
I'm running the coupled AWIESM3 model with LPJ-GUESS, and I'm having trouble getting the LPJ-GUESS restart mechanism to work across years.

We've completed a two-year simulation (with N deposition turned off for now), but I can't properly copy the LPJ-GUESS state files to the correct run directories so that the model can continue from the restart.

I tried the following approach in the `lpj_guess` section of `awiesm3.yaml:`

```
nproc: 128
proc_list_entry: '[str(x) for x in range(1,${nproc}+1)]' 
proc_list: $(( ${proc_list_entry} ))
```

And for the restart handling:

```
       restart_files:
                "state_[[proc_list-->PROC_NUM]]": "[[proc_list-->PROC_NUM - 1]].state"

        restart_in_work:
                "state_[[proc_list-->PROC_NUM]]": "runPROC_NUM/guess.restart"

        restart_sources:
                "state_[[proc_list-->PROC_NUM]]": "work/lpjg_state_{{ end_date.syear + 1 }}/[[proc_list-->PROC_NUM - 1]].state"

        file_movements:
                lpjg_restart:
                        all_directions: copy
```

Although esm-tools doesn’t crash, it also doesn’t copy the restart files at all, so LPJ-GUESS starts without the proper initial state, defeating the restart mechanism.

I suspect the problem is related to how esm-tools processes these template expressions, especially the use of `PROC_NUM - 1` in file names or paths.

Any suggestions for a working configuration would be greatly appreciated.

**Comment by JanStreffing** [comment]
I have this on my radar, but it would have to wait until after EGU. @pgierz & @mandresm, do you have time?

**Comment by mandresm** [comment]
Yes, I also had it on my radar. I will look at it today

**Comment by mandresm** [comment]
Hi @hajlaci,

The syntax is incorrect. The keys are `restart_in_in_work` and `restart_in_sources`. The explanation is here: https://esm-tools.readthedocs.io/en/latest/yaml.html#file-dictionary-types

In a nutshell, the keys of file dictionaries are composed by 2 parts: 
1. `restart_in` and `restart_out` that control which restart files go "in" before a simulation is run and "out" during tidy.
2. `_in_work`, `_sources`, `_files`, where `in_work` is used to indicate the path in `run_DATE/work`, `_sources` is the path in the source, and `_files` is to include the files and actually get the files copied/moved.

You also don't have any `restart_out` which means you are not copying/moving from `run_DATE` to the `<path_to_simulation>/restarts` so ESM-Tools cannot find your restarts in the next run.

Have a look at the documentation above and the `fesom-2.5.yaml`, that is a good one to use for inspiration.

Also the syntax for the list expansions is incorrect (the keys containing `[[-->]]`). Here is the documentation: https://esm-tools.readthedocs.io/en/latest/yaml.html#list-loops

If you provide the path of a given restart file in `work` and which name should it take in `<path_to_simulation>/restarts/lpg_guess` I can write a little snipped for you.

**Comment by hajlaci** [comment]
The LPJ-GUESS restart files are currently written by each instance at the end of a simulation year into this directory:

`<path_to_current_year_simulation>/work/lpjg_state_<next_simulation_year>/*.state`
with file names `*.state` = `0.state`, `1.state`, ..., `127.state`
Each of these corresponds to one LPJ-GUESS process.

For the next simulation leg, these files need to be copied to:
`<path_to_next_year_simulation>/work/run*/`
to directories `run*` = `run1`,` run2`, ..., `run128`

So the restart file from the process `i` must be copied as:
`i.state` → `run(i+1)/i.state`

**Comment by mandresm** [comment]
Thanks a lot @hajlaci for the broken down explanation!

> So the restart file from the process i must be copied as:
> i.state → run(i+1)/i.state

Does this mean that lpj-guess needs the restarts like this:
work/run1/0.state
work/run2/1.state
work/run3/2.state
...

Wow... that's quite a restart logic...

It can be done, I just need a confirmation that I am understanding it correctly.

**Comment by hajlaci** [comment]
Hi @mandresm

I just got a response from the LPJ-GUESS developers from LUND, and it seems that for the EC-EARTH setup, the model does not require individual `.state` files to be copied into the `run*` directories for each process. I guess the different naming was an issue for them as well. Instead, the model internally reconstructs the path to the restart files using the parameters defined in `guess.ins`. In the future, we would need to move the l`pjg_state_*/ `into the main` restarts/ `directory, but for now, I think no extra work is needed on your side.
I will test this today and get back to you if I stuck in the process.

**Comment by mandresm** [comment]
Hi @hajlaci,

>  In the future, we would need to move the lpjg_state_*/ into the mainrestarts/directory, but for now, I think no extra work is needed on your side.

I suggest you do this now and not in the future, workarounds that will be difficult and unsafe, which in the end can delay you even more. I will help with that.

What do I suggest to do then?

1. Below you ahve the logic written down in yaml to copy all the restart files from `work/lpjg_state_<next_simulation_year>/*.state` into `<exp_id>/restarts/lpj_guess/pjg_state_<next_simulation_year>`. In this way restarts are available even if a user decides to delete the `run_` directory, which is pretty common.

```yaml
lpj_guess:

    # Copy from work to general restarts
    # ----------------------------------

    # Source of the files as in <exp_id>/run_<DATE>/work/
    restart_out_sources:
        state: lpjg_state_${next_date!syear}/*.state

    # Target of the files as relative path inside <exp_id>/restarts/lpj_guess/
    restart_out_targets:
        state: lpjg_state_${next_date!syear}/*.state

    # Specify which files need to be copied using their label (e.g. "state")
    # Without specifying the label here no file is copied
    restart_out_files:
        state: state
```

Once you check that the above works, you can move on into the next step.

2. You can tell me which path `lpj_guess` needs inside `work` in the next run after you figure out a way to tell lpj_guess how to compose a path. Then I can give you another yaml snippet for that purpose.

Kind regards,
Miguel

**Comment by mandresm** [comment]
Hello @hajlaci,

The second part needed a fix in `esm_parser`. To get that fix please run `git cherry-pick -x af1aacc216b9573b369750c38aae86b06192b56d`.

Once you have the fix in the backend you can add this to your yaml:

```yaml
lpj_guess:

    # Copy from work to general restarts
    # ----------------------------------

    # Target of the files as relative path inside <exp_id>/restarts/lpj_guess/
    restart_out_sources:
        state: lpjg_state_${next_date!syear}/*.state

    # Source of the files as in <exp_id>/run_<DATE>/work/
    restart_out_in_work:
        state: lpjg_state_${next_date!syear}/*.state

    # Specify which files need to be copied using their label (e.g. "state")
    # Without specifying the label here no file is copied
    restart_out_files:
        state: state

    proc_list_entry: '[str(x) for x in range(0,${nproc})]'
    proc_list: $(( ${proc_list_entry} ))

    # Copy from work to general restarts
    # ----------------------------------

    # Source of the files as in <exp_id>/restarts/lpj_guess/
    restart_in_sources:
        "state_[[proc_list-->PROC]]": lpjg_state_${current_date!syear}/PROC.state

    # Target of the files as relative path inside <exp_id>/run_<DATE>/work/
    restart_in_in_work:
        "state_[[proc_list-->PROC]]": "run$(( PROC + 1 ))/PROC.state"

    # Specify which files need to be copied using their label (e.g. "state_PROC")
    # Without specifying the label here no file is copied
    restart_in_files:
        "state_[[proc_list-->PROC]]": state_PROC
```
