### ISSUE TITLE
Latest version breaks awiesm - pism coupling

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#1368]
**Describe the bug**
The awiesm - pism coupling via workflow manager is not working. When I try to submit a job I get the following error:

```console
ERROR: Category conflict
------------------------
Key next_setup_name exists in two different yaml files at the same hierarchical level (runscript) and have different values (awiesm:pism). To solve this remove  one of the these two values, or include them into a choose block that avoids the conflict.
- /albedo/work/user/lackerma/run_configs/awiesm_pism/awiesm_pism.yaml,line:8,col:21
- /albedo/work/user/lackerma/run_configs/awiesm_pism/awiesm_pism.yaml,line:14,col:21
```

The corresponding runscript looks like this:
```yaml
general:
        iterative_coupling: True
        use_venv: False
        base_dir: "/albedo/work/user/lackerma/experiments"
        account: "paleodyn.paleo_work"

model1:
        setup_name: awiesm
        runscript: awiesm.yaml
        chunk_size: 1
        chunk_unit: "years"

model2:
        setup_name: pism
        runscript: pism.yaml
        chunk_size: 1
        chunk_unit: "years"
```

The workflow manager expects the syntax indicated as above:

`model1` needs to be AWI-ESM
`model2` needs to be PISM

Runscripts to reproduce the error are here:
`/albedo/work/user/lackerma/run_configs/awiesm_pism`

**Additional context**
