### ISSUE TITLE
Catching errors in OpenIFS, ECHAM, NEMO etc. 

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#148]
I'd like to have a feature in OpenIFS to check the log file "ifs.stat" after every run to make sure that the number of time steps completed is the same as ESM-Tools was expecting. 
I find that OpenIFS sometimes crashes but ESM-Tools still tries a restart over and over again and it becomes hard to find the origin of the error. 
Similar "error catching" could be implemented for NEMO where the time step number is written in "time.step". 

We could read the last line in "ifs.stat" for OpenIFS or "time.step" for NEMO, extract the number and compare to "next step" in ESM-Tools. This is pretty straightforward to do in python or bash, but I don't know where we would do it. 
I think ECHAM does something similar to catch "wind speed" errors. Could we generalize that solution for other models as well? 

We could do it as a plugin, but I feel that this might be something every model might need so perhaps it should be a core feature of ESM-Tools. 

Could we somehow define a method to run a certain bash command or python command before and after the model is executed?

**Comment by pgierz** [comment]
See also #142: I guess Joakim's imagined feature qualifies as a sanity check? I'll do some brainstorming and post a (maybe) general solution later this week, we need something similar for JSBACH. Something like:

```yaml
model_name:
    sanity_checks_before_compute:
        unique_name_of_check:
            - path_of_program_to_run.sh (exit code must be 0)
            - maybe another program is here
    sanity_checks_after_post:
        another_check:
            - something
```
The user would have hooks to run checks before and after the main job, which might be a compute job, a post job, a couple job, or whatever else...

@joakimkjellsson: you'd need to write a mini shell script or something similar that does whatever check you need it to do.
