### ISSUE TITLE
ECHAM-6.3.05p2 Runtime Error with Shared Libraries

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#154]
**Describe the bug**
When running `AWIESM-2.1` on Ollie, I immediately get an error:
```
  27: /work/ollie/pgierz/test_esmtools/experiments/forced_init_test_003/run_20000101-20001231/work/./echam6: error while loading shared libraries: libsupport.so.0: cannot open shared object file: No such file or directory
```

I preformed a clean install of all the components this morning, and re-installed the model from scratch.

**To Reproduce**
You can use this runscript to reproduce the problem:
```yaml
general:
    setup_name: "awiesm"
    version: "2.1"
    compute_time: "01:00:00"
    initial_date: "2000-01-01"
    final_date: "2300-12-31"
    base_dir: "/work/ollie/pgierz/test_esmtools/experiments/"
    nmonth: 0
    nyear: 1

awiesm:
    postprocessing: false
    model_dir: "/work/ollie/pgierz/test_esmtools/model_codes/awiesm-2.1/"
    scenario: "PALEO"

echam:
    nproca: 24
    nprocb: 18
    nprocar: 24
    nprocbr: 18
    npromar: 8
    restart_rate: 1
    restart_unit: "years"

fesom:
    version: "2.0"
    res: "CORE2"
    pool_dir: "/work/ollie/pool/FESOM/"
    mesh_dir: "/work/ollie/dsidoren/input/fesom2.0/meshes/mesh_CORE2_finaltopo_mean/"
    restart_rate: 1
    restart_unit: "y"
    restart_first: 1
    lresume: 0
```

**System (please complete the following information):**
 - Supercomputer: ollie
 - Version:
```
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.3
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.6 (development install, on branch: release, describe=v4.2.6-1-g4116b68)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.5.0
```

**Additional Info**

Probably, this has something to do with one of the modules on ollie? `AWIESM-2.1` is the only model that uses `ECHAM-6.3.05p2 with concurrent radiation` and configure/autotools rather than CMake. I can test and see if this happens with the regular AWICM-2.
