### ISSUE TITLE
Restart files not found when resuming ECHAM

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#159]
Maybe related to #130 

**Describe the bug**
When restarting AWI-CM-2.0 or ECHAM standalone from a previous experiment, ECHAM crashes with the following error:
`  1: FATAL ERROR in : restart file not available !
  1:  FINISH called from PE: 1`

lresume for FESOM is working fine.

```
general:
    setup_name: "awicm"
    version: "2.0"
    compute_time: "01:00:00"
    initial_date: "2000-01-01"
    final_date: "2300-12-31"
    base_dir: "/work/ollie/lackerma/awicm_pism_tests"
    nmonth: 0
    nyear: 1
awicm:
    postprocessing: false
    model_dir: "/home/ollie/lackerma/awicm-2.0"
    scenario: "PALEO"
    lresume: 1
echam:
    nproca: 24
    nprocb: 18
    nprocar: 0
    nprocbr: 0
    npromar: 8
    restart_rate: 1
    restart_unit: "years"
    lresume: 1
    ini_restart_dir: "/work/ollie/sxu/AWICM-2.0/restart_files/picontrol/"
    ini_parent_exp_id: "picontrol"
    ini_parent_date: 30991231
fesom:
    version: "2.0"
    res: "CORE2"
    pool_dir: "/work/ollie/pool/FESOM/"
    mesh_dir: "/work/ollie/sxu/AWICM-2.0/meshes/core2_dkrz/"
    restart_rate: 1
    restart_unit: "y"
    restart_first: 1
    ini_restart_dir: "/work/ollie/sxu/AWICM-2.0/restart_files/picontrol/"
    ini_parent_exp_id: "picontrol"
    ini_parent_date: 30991231
    lresume: 1
```

**System (please complete the following information):**
 - Supercomputer: Ollie
 - Version: 
```
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.3
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.6 (development install, on branch: release, describe=v4.2.6-1-g4116b68-dirty)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.5.0
```

**Additional context**
I could not find any hind in the documentation.
Links to the experiments:
`/work/ollie/lackerma/awicm_pism_tests/paul_restart02`
`/work/ollie/lackerma/awicm_pism_tests/echam01`
