### ISSUE TITLE
Can only do add_forcing_data once per yaml file? 

### ISSUE THREAD

**Issue by joakimkjellsson** [esm-tools/esm_tools#16]
Hi all

I noticed something odd with my oifs.yaml. In one place there is 
```
add_export_vars:
        DR_HOOK_IGNORE_SIGNALS: "-1"
        OIFS_EXPID: ${input_expid}
        FOCI_USE_CPLNG: "no"
        AWICM_USE_CPLNG: "no"
        ECE_USE_CPLNG: "no" 
```
and towards the end of oifs.yaml there is also
```
choose_version:
        40r1:
                environment_changes:
                        add_export_vars:        
                                - 'OIFS_FFIXED="-fixed"' 
```

However, only the last one is ever executed. The first "add_export_vars" are never added. 
I also tried to have two "add_forcing_files" statements, and only one of them was executed. 

Can there only be one "add_forcing_files" or "add_export_vars" or "add_input_files" per yaml file? 
Is it possible to add the ability to have several? Does anyone have an example? 

Cheers
Joakim
