### ISSUE TITLE
`choose_version` in `echam.yaml` does not work in standalone setups

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#164]
**Describe the bug**
Variables that are set in `choose_version` in `echam.yaml` do not overwrite the defaults. If no defaults are set, the variables defined in `choose_version` are used.

**To Reproduce**
set the following in `echam.yaml`
```yaml
version:  6.3.05p2-foci
dataset: r0007
choose_version:
        6.3.05p2-foci:
                dataset: r0008 
```
You would expect that that `dataset: r0008.yaml` in the final config, but `r0007` is used. If I comment the default value, i.e.
```yaml
version:  6.3.05p2-foci
#dataset: r0007
choose_version:
        6.3.05p2-foci:
                dataset: r0008 
```
`dataset: r0008` is used in the final yaml file.
I tested this with other test variables that I set in the `choose_version` block. Same effect. Also for other versions of echam.
Is it me being stupid here, or is it a real bug. As it seems to work in all other cases, I was hesitant to file a bug report.
Could it be related to the fact that ECHAM6 is both a setup and a component at the same time if used in uncoupled mode?

**Expected behavior**
The default value should be overwritten as it works in all other cases e.g. for jsbach.yaml

**System (please complete the following information):**
 - Supercomputer: blogin
 - Version: latest release
