### ISSUE TITLE
Wrong jsbach files for no-dynveg and unnecessary streams

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#174]
Vanessa (AWI Bremerhaven) reported the following bug via email.

**Describe the bug**
I am using ECHAM T127, but without dynamic vegetation. But instead of only using jsbach_T127GLOB_11tiles_5layers_1850_no-dynveg.nc , it still searches for jsbach_T127GLOB_11tiles_1851.nc. I know, it takes the info from the config file for jsbach, but I am unsure how to change it. I included dynamic_vegetations: false in the yaml file, but that does not seem to be enough.

Secondly, I do not include the nitrogen cycle, How do I switch it off?

**To Reproduce**
Using the following runscript:
```
general:
     setup_name: "awicm"
     account: b0246
     compute_time: "00:25:00"
     expid: "hist1_old_mesh"
awicm:
     version: "CMIP6"
     scenario: "HIST"
     post_processing: 0
     initial_date: "1851-01-01"
     final_date: "1851-02-01"
     model_dir: /pf/a/a270152/model_codes/awicm-CMIP6/
     base_dir: /work/ab0246/a270152/esm_yaml_test/
     pool_dir: /pool/data/
     resolution: T127
     nyear: 0
     nmonth: 1
fesom:
     lresume: 1 
     pool_dir: /work/bm0944/input/
     mesh_dir: /pool/data/AWICM/FESOM1/MESHES/glob/
     resolution: GLOB
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/fesom/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
     first_initial_year: 1850
     restart_rate: 1
     restart_first: 1
     restart_unit: "m" 
     further_reading: "fesom_output_control.yaml"
echam:
     resolution: "T127"
     lresume: 1
     scenario: "HIST" 
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/echam/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
     dataset: r0007
     nproca: 24
     nprocb: 48
     disturbed_years: 2013
     disturbance: 1.00001
oasis3mct:
     lresume: 1
#     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/input/oasis3mct/
     ini_restart_dir: /work/ba1150/a270147/hist1_oasis_restart/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
jsbach:
    ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/jsbach/
    dataset: r0009
    dynamic_vegetations: false

hdmodel:
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/hdmodel/
```

**Expected behavior**
ESM-Tools loads the correct files when `dynamic_vegetations` is set to `false` and that streams are selected based on the user's choices.

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]

**Additional context**
Experiment type restart AWICM-CMIP6

**Comment by mandresm** [comment]
**Provisional solution**
Add the following to the runscript:
```
    streams:
        - jsbach
        - jsbid
        - yasso
        - surf
        - land
    add_forcing_sources:
        "cover_fract_HIST":
            "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_1850${jsbachnc_file_ending}.nc"
```

I'll be working asap on a fix.

**Comment by mandresm** [comment]
@jobo95 pointed out via email:
"Also a minor point what I think might be a bit confusing is that it is e.g. reporting and looking for these  dynamical vegetation missing files in the beginning, although they are not used at all when  dynamical vegetation is turned off..."

I think this is relevant to this issue so I included here. @jobo95 , feel free to add more details about it.

**Comment by ghost** [comment]
> 
> 
> @jobo95 pointed out via email:
> "Also a minor point what I think might be a bit confusing is that it is e.g. reporting and looking for these dynamical vegetation missing files in the beginning, although they are not used at all when dynamical vegetation is turned off..."
> 
> I think this is relevant to this issue so I included here. @jobo95 , feel free to add more details about it.

Hi, in my case I started an ECHAM standalone simulation with e.g. a runscript of the following form: 

```
general:
        setup_name: echam
        account: bb1152
        compute_time: "08:00:00"
        post_time: "01:00:00"

        initial_date: "1850-01-01"
        final_date: "1850-03-31"

        base_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments"
        model_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/echam-6.3.04p1"

        nyear: 0
        nmonth: 1

echam:
        scenario: "PI-CTRL"
        version: "6.3.04p1"
        bin_dir: ${model_dir}/src/echam/bin/HICE_thickness_sara
        namelist_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/esm_tools/namelists/echam/6.3.04p1/Johannes"
        #pool_dir: /pool/data
        resolution: T127
        ocean_resolution: TP04
        levels: L95

        lresume: False
        #restart_unit: "years"
        restart_unit: "months"
        restart_rate: 1
        restart_first: 1
        nproca: 24
        nprocb: 48

        add_forcing_sources:
                pisst: /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/T127_HadNOAAOI_SST_LAMO.nc
                pisic: /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/T127_HadNOAAOI_SIC_HICE.nc


jsbach:
        namelist_dir: "/work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/esm_tools/namelists/jsbach/3.20/Johannes"
        dynamic_vegetations: False
        dataset: r0009
        #dynveg: False

```

and got some reported missing forcing files:

```
MISSING FILES:
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//landuse_harvest.1850.nc:
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//landuse_harvest.1849.nc:
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//landuse_harvest.1851.nc:
        --> /pool/data/JSBACH/input/r0009/T127/New_Hampshire_LCC/hist_harvest/LUH_harvest_T127_1850.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//a_nd_file.nc:
        --> /pool/data/JSBACH/input/r0009/T127/spitfire/a_nd_T127.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//lightning.nc:
        --> /pool/data/JSBACH/input/r0009/T127/spitfire/LISOTD_HRMC_V2.2_T127.nc
--  /work/bb1152/Module_A/A3_ArcClimEx/a271093_riebold/model_codes/Experiments/test_run_new2/run_18500101-18501231/forcing/jsbach//population_density.nc:
        --> /pool/data/JSBACH/input/r0009/T127/spitfire/population_density_HYDE_T127.nc
```

I mean, when looking into the JSBACH config file:

```
choose_version:

.........

"3.20":
                dataset: r0010
                choose_dynamic_vegetations:
                        true:
                                namelist_dir: "${general.esm_namelist_dir}/jsbach/${version}/${echam.scenario}/dynveg"
                                dynveg: "_dynveg"
                                jsbachnc_file_ending: "${dynveg_file_ending}"
                        false:
                                namelist_dir: "${general.esm_namelist_dir}/jsbach/${version}/${echam.scenario}/no_dynveg"
                                jsbachnc_file_ending: "${no_dynveg_file_ending}"
                                dynveg: "_no_dynveg"
                choose_echam.scenario:
                        PI-CTRL:
                                add_input_files:
                                        jsbach: jsbach_1850
                                forcing_files:
                                        LU: LU_1850
                                        LU_trans: LU_trans_none
                                        Ndepo: Ndepo_1850
                                        a_nd_file: a_nd_file
                                        lightning: lightning
                                        popdens: popdens
 
........

HIST:
                                add_input_files:
                                        jsbach: jsbach_1850
                                forcing_files:
                                        LU: LU_HIST
                                        LU_trans: LU_trans_none
                                        cover_fract: cover_fract_HIST
```

for my PI-CTRL scenario it's just looking for the forcing files stated there (and doesn't find some of them). But I do not see where it distinguishes bewtween dynamic and non-dynamic vegetation. In my case it's not finding these forcing files in the paths,and according to the ECHAM docs dynamic vegetation should only be used when `USEDYNVEG= .TRUE` is explicitely set in the namelist (which is not the case at least in my case). So I guess finally everthing is fine, but it's still kind of confusing ...   As I am also lacking knowledge about JSBACH and its docs, I am currently not sure which (or if) data from which forcing files should be used for non-dynamical vegetation...

In Vanessa's HIST scenario it's just looking for this `jsbach_T127GLOB_11tiles_1851.nc ` forcing file as it's defined in the jsbach.dataset file fwhen starting 1851: 

```
input_sources:
        lctlib: "${echam.model_dir}/lctlib_nlct21.def"
        "jsbach_1850": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1850${jsbachnc_file_ending}.nc"
        "jsbach_1976": "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_5layers_1850${jsbachnc_file_ending}.nc"

.....

forcing_sources:
        "LU_1850": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc"
        "LU_1950": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1950.nc"
        "LU_HIST":
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_1850.nc":
                        to: 1850
                "${input_dir}/${echam.resolution}/New_Hampshire_LCC/${hist_fold}/LUH_harvest_${echam.resolution}_@YEAR@.nc":
                        from: 1851
        "cover_fract_HIST":
               "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_1850.nc":
                        to: 1850
               "${adj_input_dir}/jsbach_${echam.resolution}${echam.ocean_resolution}_11tiles_@YEAR@.nc":
                        from: 1851
        "LU_trans_none": "${input_dir}/${echam.resolution}/New_Hampshire_LCC/no_LUH_transitions_${echam.resolution}.nc"
```

Normally, it should also look for e.g. this `LUH_harvest_T127_185?.nc` forcing file hist scenario, nor? 

 `jsbach_T127GLOB_11tiles_5layers_1850_no-dynveg.nc` should be an input file, so should have nothing to do with the forcing file stated above..
