### ISSUE TITLE
Error when reading ocean restart files

### ISSUE THREAD

**Issue by vkolatschek** [esm-tools/esm_tools#211]
**Describe the problem**
I am using AWI-CM (CMIP6) to branch of an existing historical scenario run of the CMIP6 simulations. When reading the ocean restart files, it produces this error:
```
Ocean matrices have been set up
Ocean arrays have been set up
read ocean restart file
Error:
NetCDF: Invalid dimension ID or name

Error:
NetCDF: Invalid dimension ID or name

Error:
NetCDF: Invalid dimension ID or name
```
Additionally, the model does not crash, but continues to try to read the restart files until the time limit (in this case 2 h) is reached.

**To Reproduce**
`esm_runscripts awicm-mistral_hist1_trial.yaml -e hist1_restart`

**Runscript and other relevant files**
My runscript:
```
general:
     setup_name: "awicm"
     account: ba1150
     compute_time: "02:00:00"
awicm:
     version: "CMIP6"
     scenario: "HIST"
     post_processing: 0
     initial_date: "1851-01-01"
     final_date: "1851-02-01"
     model_dir: /pf/a/a270147/awicm-CMIP6/
     base_dir: /work/ba1150/a270147/awicm-CMIP6/
     pool_dir: /pool/data/
     resolution: T127
     nyear: 0
     nmonth: 1
fesom:
     lresume: 1
     pool_dir: /work/bm0944/input/
     mesh_dir: /pool/data/AWICM/FESOM1/MESHES/glob/
     resolution: GLOB
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/fesom/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
     first_initial_year: 1850
     restart_rate: 1
     restart_first: 1
     restart_unit: "m"
     further_reading: "fesom_output_control.yaml"
echam:
     resolution: "T127"
     lresume: 1
     scenario: "HIST"
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/echam/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
     dataset: r0007
     nproca: 24
     nprocb: 48
     disturbed_years: 2013
     disturbance: 1.00001
oasis3mct:
     lresume: 1
     ini_restart_dir: /work/ba1150/a270147/hist1_oasis_restart/
     ini_parent_date: 18501231
     ini_parent_exp_id: "hist1"
jsbach:
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/jsbach/
     dataset: r0010
     dynamic_vegetations: false
     streams:
          - jsbach
          - jsbid
          - yasso
          - surf
          - veg
hdmodel:
     ini_restart_dir: /work/bk0988/awicm/a270062/AWICM/hist1/restart/hdmodel/
```

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version:
```
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar: 4.0.1
esm_database: 4.0.0
esm_environment: 4.2.0
esm_master: 4.2.2
esm_parser: 4.2.1
esm_profile: 4.0.0
esm_rcfile: 4.0.0
esm_runscripts: 4.2.1
esm_tools: 4.2.10 (development install, on branch: hotfix/issue174, describe=v4.2.9-8-gc27fee5)
esm_plugin_manager: 4.2.0
esm_version_checker: 4.4.0
```

**Additional context**
The dimension read (and probably producing the error) is the time dimension in the ocean restart files. The dimension name in the file is 'T', but in the model code (gen_input.F90) it is called 'time'.
