### ISSUE TITLE
empty add_ block causes unexpected behaviour

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#215]
**Describe the bug**
During a test I ended up with the following block in a yaml file (do you spot the error :-) ):
```yaml
...
runtime_environment_changes:
  choose_computer.name:
    blogin:
      add_module_actions:
      add_export_vars:
        - 'OIFS_FFIXED=""'
        - 'GRIB_SAMPLES_PATH="$ECCODESROOT/share/eccodes/ifs_samples/grib1_mlgrib2/"'
        - 'DR_HOOK_IGNORE_SIGNALS="-1"'
...
```
In the above case the settings below weren't used as expected and e.g. the export vars not set. **WARNING: I can't exactly recall, whether the setup was exactly as described above, but maybe it's still helpful to check if empty sections are handled correctly.**
**To Reproduce**
Well, just do the same (stupid) thing that I did

**Expected behavior**
Not use the block `add_module_actions: ` and continue

**System (please complete the following information):**
 - system independent

**Additional context**
**WARNING: I can't exactly recall, whether the setup was exactly as described above, but maybe it's still helpful to check if empty sections are handled correctly.**

**Comment by JanStreffing** [comment]
I just did a test run with:
```
fesom:
    add_export_vars:
    add_namelist_changes:
        namelist.oce:
            oce_dyn:
                gamma0: "1"
```
The empty add block did not trip up esm_tools. I assume the issue is solved. Closing here. If it reappears, reopen please.
