### ISSUE TITLE
venv not working when preprocess plugin is required.

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#229]
**Describe the bug**
As we have to install the preprocess plugin for OIFS manually at the moment:
```bash
cd /path/to/where/I/install/plugins
git clone https://github.com/esm-tools-plugins/preprocess.git
cd preprocess
module load my_python3_module
pip install --user -e .
```
it is not installed during the venv generation and hence and OIFS runscript fails after the venv has been created.

**To Reproduce**
Run an OIFS of FOCIOIFS runscript in a venv.

**Expected behavior**
Plugins should be installed automagically, I remember that @pgierz mentioned at some point that this should work.

**System (please complete the following information):**
 - Supercomputer: does not matter
 - Version: 5.0 and below

**Comment by seb-wahl** [comment]
See also https://github.com/esm-tools/esm_tools/issues/112

**Comment by pgierz** [comment]
Magic may not be needed here, but I'll have a look :-) Can you check if the plugin is written down in your YAML file? 

The venv_bootstrap program installs any plugins listed:

https://github.com/esm-tools/esm_runscripts/blob/2916a282ced46f1a988dc8b54adfadb37cca7793/esm_runscripts/virtual_env_builder.py#L87-L94
```python
def _install_required_plugins(venv_context, config):
    required_plugins = []
    for sub_cfg in config.items():
        if isinstance(sub_cfg, dict):
            if "required_plugins" in sub_cfg:
                required_plugins += sub_cfg["required_plugins"]
    for required_plugin in required_plugins:
        _run_bin_in_venv(venv_context, ["pip", "install", '-q', required_plugin])
```

So, in your OIFS yaml, you would need to have a section:
```yaml
oifs:
    required_plugins:
        - "git+https://github.com/esm-tools-plugins/preprocess"
```

Although, looking at that, it may have a bug. I don't think `config.items()` is correct, it might need to be `config.values()`...

**Comment by seb-wahl** [comment]
I tried what you suggested, and I still get the same error when I try to run FOCIOIFS. I added the require_plugins line to `oifs.yaml`.

**Comment by pgierz** [comment]
Ok, I have a fix, can you please test https://github.com/esm-tools/esm_runscripts/pull/46?

**Comment by pgierz** [comment]
And, this is why you aren't getting your plugin installed :-(

```python
>>> d = {1: "a", 2: "b", 3: "c"}
>>> d.items()
dict_items([(1, 'a'), (2, 'b'), (3, 'c')])
>>> for i in d.items():
...    print(i)
...    print(type(i))
... 
(1, 'a')
<class 'tuple'>
(2, 'b')
<class 'tuple'>
(3, 'c')
<class 'tuple'>
>>> 
```

**Comment by seb-wahl** [comment]
Still the same error. I used:
```yaml
general:
   install_esm_tools_branch: "feature/geomar-setup"
   install_esm_runscripts_branch: "hotfix/venv_install_plugins"
```
and committed all my changes to `feature/geomar-setup` before starting the test, except for the yaml runscript itself (if that's relevant)

**Comment by pgierz** [comment]
So, for me, this works. I have the following:

1) A test script to emulate "preprocess" from the shell
```
$ cat ${HOME}/beep.sh
#!/bin/bash

echo "Beep beep beep!"
```
2) A up-to-date installation of all the packages to version 5.0
3) A development install of esm-runscripts to branch `hotfix/venv_install_plugins`
4) A slightly modified echam.yaml file to include the preprocess plugin:
```diff
diff --git a/configs/components/echam/echam.yaml b/configs/components/echam/echam.yaml
index 1b5eacf..4005d59 100644
--- a/configs/components/echam/echam.yaml
+++ b/configs/components/echam/echam.yaml
@@ -102,6 +102,10 @@ choose_computer.name:
                             - "NETCDFROOT=/sw/rhel6-x64/netcdf/netcdf_c-4.3.2-gcc48"
                             - "LD_LIBRARY_PATH=/sw/rhel6-x64/netcdf/parallel_netcdf-1.6.1-impi-intel14/lib/:$LD_LIBRARY_PATH"
 
+
+required_plugins:
+    - "git+https://github.com/esm-tools-plugins/preprocess.git"
+
 executable: echam6
 version: 6.3.04p1
 resolution: T63
```
5) This runscript:
```yaml
general:
    setup_name: "awiesm"
    version: "2.1"
    compute_time: "00:20:00"
    initial_date: "2000-01-01"
    final_date: "2300-12-31"
    base_dir: "/work/ollie/pgierz/test_esmtools/experiments/"
    nmonth: 1
    nyear: 0
    use_venv: True
    install_esm_runscripts_branch: "hotfix/venv_install_plugins"

    compute_recipe:
            - "venv_bootstrap"
            - "preprocess"


awiesm:
    postprocessing: false
    model_dir: "/work/ollie/pgierz/PalModII/model_codes/awiesm-2.1/"
    scenario: "PALEO"

echam:
    nproca: 24
    nprocb: 18
    nprocar: 24
    nprocbr: 18
    npromar: 8
    restart_rate: 1
    restart_unit: "months"
    preprocess:
            preprocess_shell:
                    method: "$HOME/beep.sh"
                    type: shell

fesom:
    version: "2.0"
    res: "CORE2"
    pool_dir: "/work/ollie/pool/FESOM/"
    mesh_dir: "/work/ollie/dsidoren/input/fesom2.0/meshes/mesh_CORE2_finaltopo_mean/"
    restart_rate: 1
    restart_unit: "m"
    restart_first: 1
    lresume: 0
```

Important part os the modified compute recipe, and the small preprocess section inside of echam.

Running that gives me:
```
$ esm_runscripts seb_run.yaml -e seb_09
Building virtual env, please be patient (this takes about 3 minutes)...
...finished 0:04:10.697858, restarting your job in the virtual env
Beep beep beep!
```

Of course, this may be an over-simplified case, but I think it should work with the full GEOMAR model as well.

**Comment by seb-wahl** [comment]
I was able to get it to work now. With both `esm_tools` and `esm_runscripts` being on the same branch than the one I set in the runscript:
```yaml
general:
   install_esm_tools_branch: "feature/geomar-setup"
   install_esm_runscripts_branch: "hotfix/venv_install_plugins"
```
I haven't tested though whether I can be on another branch of `esm_tools` when creating the runtime environment...
