### ISSUE TITLE
Functionality to change component variables from setups in esm_master

### ISSUE THREAD

**Issue by mandresm** [esm-tools/esm_tools#32]
An example of the desired functionality would be to modify the `conf_command` of MPIOM from the MPIESM setup, so that we can run `./config` with different flags if MPIOM is standalone or coupled.

Component configuration in `setups2models`:
```
components:
        "mpiom":
                install_bins: "bin/mpiom.x"
                git-repository: "https://gitlab.dkrz.de/modular_esm/mpiom.git"
                choose_version:
                        "1.6.2p3":
                                branch: "1.6.2p3"
                        "1.6.3":
                                branch: "1.6.3"
                        "1.6.3p2":
                                branch: "1.6.3p2"
                available_versions:
                        - "1.6.2p3"
                        - "1.6.3"
                        - "1.6.3p2"
                conf_command: "./configure --prefix=${model_dir} --disable-mh-file --enable-HAMOCC"
                comp_command: "make"
                clean_command: "${defaults.clean_command}"
```

Then we should be able to define a different `conf_command` in the MPIESM setup or coupling, for example:
```
setups:
        mpiesm:
                available_versions:
                        - "1.2.00p4"
                        - "1.2.01"
                        - "1.2.01p1"

                choose_version:
                        "1.2.00p4":
                                couplings:
                                        - "mpiom-1.6.2p3+echam-6.3.02p4"
                                mpiom:
                                        conf_command: "./configure --prefix=${model_dir} --disable-mh-fil    e --with-coupler=oasis3-mct --enable-HAMOCC"
                        "1.2.01":
                                couplings:
                                        - "mpiom-1.6.3+echam-6.3.04p1"
                        "1.2.01p1":
                                couplings:
                                        - "mpiom-1.6.3p2+echam-6.3.05p2"
```
