### ISSUE TITLE
Version dependence in Setup Yaml

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#347]
Moin guys,

I have what may be a bit of a crazy request, but I need to able to set particular namelist settings based upon the git hash of the model. I know that we are already able to differentiate between various tagged versions, but is there any way to get the commit number?

In shell, it'd be easy enough, something like:

```shell
case $(git rev-parse --short HEAD)
    pauls_favorite_commit)
        do something cool
        ;;
    *)
        don't do something cool
        ;;
esac
```

**Comment by pgierz** [comment]
For added bonus points, it might be useful to see and define settings based on "is that commit as old or newer than X". But I get the feeling we'd need to dig fairly deep into our parse to get that to work.

**Comment by mandresm** [comment]
Hi @pgierz , @JanStreffing and I have been already discussing about the need of ESM-Tools registering the commit ID of the models used. I think this is a fairly simple development that can be added as another step to the `prepare` recipe. We could also add to this step the features you are asking for. What do you think?

In my opinion this potential new step/method should do the following:
1. Write a `versions.yaml` file inside the `config`? folder containing something like this:
   ```
   esm_tools:
       esm_runscripts: 5.1.6
       esm_parser: 5.1.2
       ...
   fesom:
      branch: <whatever branch>
      commit_id: <whatever commit id>
      parent_tag: <the closest tag>
      ...
   ```
2. Provide to the config the info you are requesting.

Producing a `versions.yaml` file during prepare might allow us to develop a feature in the future to come back to that exact configuration.

Should we use this issue to brain storm this potential development and decide if it should go into release 6.0?

**Comment by JanStreffing** [comment]
I suggest to define a choose version that contains the git commit id as the branch name. You can then set your namelist settings based on that version. e.g. replace `awicm-3-frontiers` in
```
compile_infos:
        requires:
        - oasis3mct-4.0
        available_versions:
        - 43r3-awicm-3.0
        - 43r3-awicm-frontiers
        choose_version:
          43r3-awicm-frontiers:
            requires:
            - oasis3mct-4.0-awicm-frontiers
            branch: awicm-3-frontiers
```

There seems to have been little movement on this issue. Closing here for now.
