### ISSUE TITLE
AWICM3 oasis paths with more degrees of freedom

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#364]
After discussion between Miguel and myself it became clear that we need another degree of freedom in the oasis pool directory path. Currently it goes e.g.

`/mnt/lustre01/work/ab0246/a270092/input/oasis/cy43r3/TCO319-D3/2520`

- Base: `/mnt/lustre01/work/ab0246/a270092/input/oasis/`
- OpenIFS version: `cy43r3`
- OpenIFS grid: `TCO319`
- FESOM2 mesh: `D3`
- FESOM2 distribution size: `2520`

The grids areas masks files are located at:
`/mnt/lustre01/work/ab0246/a270092/input/oasis/cy43r3/TCO319-D3/`
While the rmp and rst files are at
`/mnt/lustre01/work/ab0246/a270092/input/oasis/cy43r3/TCO319-D3/2520`

When changing the number and or choice of coupling fields the rst files need to change. Therefore rst files should at some point be moved to
`/mnt/lustre01/work/ab0246/a270092/input/oasis/cy43r3/TCO319-D3/2520/${coupling_name}`

Where coupling name is for example: `deck, frontiers, icepack_option_1, icepack_option_2`...

This is not urgent, but we wanted to collect the ideas we formulated now for a later implementation.

**Comment by JanStreffing** [comment]
Esm tools is capable of renaming the oasis restart files while linking them from pool dir to the work dir. Thus we can provide this flexibility by just having muplitly restart files with different names in the same pool dir. We can then link in with:

```
    coupling_target_fields:
        rstos.nc:
            - 'A_SST:A_Ice_frac:A_Snow_thickness:A_Ice_temp:A_Ice_albedo <--gauswgt_i-- sst_feom:sie_feom:snt_feom:ist_feom:sia_feom'
            - 'A_CurX:A_CurY <--gauswgt_i-- u_feom:v_feom'
    add_restart_in_sources:
        rmp: ${input_dir}/${fesom.nproc}/rmp_*.nc
        rstas.nc: ${input_dir}/${fesom.nproc}/rstas_uv.nc
        rstos.nc: ${input_dir}/${fesom.nproc}/rstos_uv.nc
```
A larger rework is thus not needed. Closing here.
