### ISSUE TITLE
how to test model defaults of models own fortran namelist

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#378]
**Describe the problem you are facing**
Normally the models (or components) come with their own namelist defaults, e.g. written directly in some fortran file. `esm_runscripts runscript` uses namelist entries provided by esm tools (`esm_tools/namelists/<component>`) to generate namelists which will be used by the model.

Now someone, without thinking of the esm tools, changes the model code, including a change in the default namelist of the model (i.e. in the fortran file). I checkout to this code and test it with `esm_runscripts runscript`. The problem now is that the new namelist default from the fortran file will not be used since the unchanged namelist entry from `esm_tools/namelists/<component>` will be used.

Is there a way to run a component or setup with the pure model defaults only (i.e. taken from the fortran files)? Maybe something like `esm_runscripts runscript --use-model-defaults` that creates empty namelists or so? 

Thanks for help and cheers,
Chris

**Comment by denizural** [comment]
Hi @chrisdane,
in your runscript you can set the `namelist_dir` variable. Suppose that you would like to give a manual directory for Echam namelist instead of the ESM-Tools default namelist directory (eg. `esm_tools/namelists/echam/...`. Then, in your runscript

```yaml
general:
    ...
echam:
    ....
    namelist_dir: "directory where your namelist.echam is found"
```

Make sure that you first run it with `--check` and `--verbose` and verify that the `namelist.echam` in the experiment work directory is taken from the `namelist_dir` that you provide in your runscript. 

I hope this works.

**Comment by chrisdane** [comment]
Great that seems to work. The runscript entry
```yaml
recom:
    namelist_dir: "/pf/a/a270073/esm/runscripts/"
    namelist_changes:
        namelist.recom:
            pavariables:
              REcoMDataPath: '/work/ba1103/a270094/MarESys/forcing/CORE2mesh/'
```
with the empty namelist.recom
```bash
$ cat /pf/a/a270073/esm/runscripts/namelist.recom
! empty namelist
```
results in the namelist.recom in the work directory after `esm_runscripts -c`
```bash
&pavariables
    bgc_num = 22
    recomdatapath = '/work/ba1103/a270094/MarESys/forcing/CORE2mesh/'
    constant_co2 = .true.
    firstyearoffesomcycle = 1950
    lastyearoffesomcycle = 1950
    numofco2cycles = 1
    currentco2cycle = 1
    recom_pi = .true.
    recom_restart = .false.
/

&paco2_flux_param
    co2_for_spinup = 278
/
```
Question: where do these values come from?

Small issue: path expansion with `~` is not fully supported. If I write 
```yaml
    namelist_dir: "~/esm/runscripts/"
```
instead of the absolute path in the runscript, `esm_runscripts -c` wrongly complains that `namelist.recom` is missing, although the same namelist.recom as above is created in the work directory.

The model crashes immediately:
```bash
760: forrtl: severe (24): end-of-file during read, unit 20, file /mnt/lustre02/work/ba1103/a270073/out/awicm-1.0-recom/re2751c9e_blank_nml/run_19500101-195001
31/work/namelist.recom, line 16, position 0
760: fesom              000000000047E3F5  read_namelist_             90  gen_setup_model.F90
```
while reading
```fortran
# gen_setup_model.F90
90  read (20,NML=pasinking)
```
as the chapter "pasinking" is not in the namelist.

Thanks a lot!

**Comment by denizural** [comment]
> Question: where do these values come from?

They are coming from `recom.yaml`:
```yaml
namelist_changes:
    namelist.recom:
        pavariables:
            bgc_num: 22
            REcoMDataPath: "${data_path}"
            constant_CO2: "${constant_CO2}"
            firstyearoffesomcycle: "${firstyearoffesomcycle}"
            lastyearoffesomcycle: "${lastyearoffesomcycle}"
            numofCO2cycles: "${numofCO2cycles}"
            currentCO2cycle: "${currentCO2cycle}"
            REcoM_PI: "${REcoM_PI}"
        paco2_flux_param:
            CO2_for_spinup: "${CO2_for_spinup}"
```
ESM-Tools implements a hierarchy of configuration files, where the user file overwrites everything else. Do you want a feature to completely overwrite the default settings?

---

> Small issue: path expansion with `~` is not fully supported. 

I don't really consider this as an issue since `~` is a _Linux shell expansion_. Only the Linux shell will understand it but Python won't. 
So how can we get an environment variable into our runscript? There is a feature that Paul and I implemented into esm-tools. Whenever you want to use a Linux environment variable, use this syntax:
```yaml
home: !ENV ${HOME}
namelist_dir: "${home}/esm/runscripts"
```

`!ENV` tag tell esm-tools that the following part is an environment variable eg. `!ENV ${FOO}` will return you the value wheyn you `echo ${FOO}`.

I tested this case and it seems to be working. If you want a feature that will completely overwrite the defaults then I need to spend some more time on it but it sounds like a good feature to have. Sometimes the users may want to overwrite the defaults completely.
