### ISSUE TITLE
fesom restart only does not work in echam+fesom coupled setup

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#390]
**Describe the bug**
In a coupled echam+fesom+recom experiment, I need to restart fesom (and recom) only from a coupled echam+fesom+recom experiment. In the [branching off docu](https://esm-tools.readthedocs.io/en/latest/recipes/how_to_run.html?highlight=restart#how-to-setup-runscripts-for-different-kind-of-experiments) its written that
```yaml
general:
    lresume: 1
    ini_parent_exp_id: <old-experiment-id>
    ini_restart_dir: <path-to-restart-dir-of-old-experiment>/restart/
```
needs to be in the runscript.

With 
```yaml
general:
    lresume: True
    ini_parent_exp_id: test
    ini_restart_dir: /work/ba1103/a270094/AWIESM/test/restart/
echam:
    lresume: False
jsbach:
    lresume: False
hdmodel:
    lresume: False
fesom:
    lresume: "${general.lresume}"
recom:
    lresume: "${general.lresume}"
oasis3mct:
    lresume: False
```
esm_runscripts complains that
```
==============================================================================
::: Executing the step:  set_parent_info    (step [9/15] of the job:  prepare)
==============================================================================
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/prepare.py", line 632, in set_parent_info
    config[model]["parent_date"] = config[model]["ini_parent_date"]
KeyError: 'ini_parent_date'
```
When I add
```yaml
general:
    ini_parent_date: 2685
```
the error changes to
```
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/prepare.py", line 633, in set_parent_info
    config[model]["parent_restart_dir"] = config[model]["ini_parent_dir"]
KeyError: 'ini_parent_dir'
```
When I add
```yaml
general:
    ini_parent_dir: /work/ba1103/a270094/AWIESM/test/
```
the error changes to
```
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_calendar/esm_calendar.py", line 306, in __init__
    int, ndate
ValueError: invalid literal for int() with base 10: ''
```
When I change `ini_parent_date` to
```yaml
general:
    ini_parent_date: "2685-12-31"
```
the error changes to 
```
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_parser/esm_parser.py", line 1845, in actually_find_variable
    raise EsmParserError("Sorry, a variable was not resolved: %s not found" % (rhs))
esm_parser.esm_parser.EsmParserError: Sorry, a variable was not resolved: first_initial_year not found
```
When I add
```yaml
general:
    first_initial_year: 2686
```
there are missing files such as
```
- missing source: /work/ba1103/a270094/AWIESM/test/fesomfesom.26851231.oce.nc
```
When I change `ini_parent_dir` to
```yaml
general:
    ini_parent_dir: /work/ba1103/a270094/AWIESM/test/restart/
```
the error remains. Changing
```yaml
general:
    ini_parent_dir: /work/ba1103/a270094/AWIESM/test/restart/
```
to
```yaml
fesom:
    ini_parent_dir: "${ini_restart_dir}/fesom/"
recom:
    ini_parent_dir: "${ini_restart_dir}/fesom/"
```
the error changes to
```
- missing source: /work/ba1103/a270094/AWIESM/test/restart/fesom/fesom.26851231.oce.nc
```
Putting `ini_parent_date` to the respective fesom and recom chapters does not help, also if changed to 2685, i.e. omitting the month and day.

I think this is unrelated to using or not using recom. The docu is wrong. I neither can find `ini_parent_dir` in any of the default runscripts nor in the documentation. The options in `esm_tools/runscripts/fesom-recom/fesom-recom-ollie-restart-control.yaml` do not solve my problem (as shown above). Also, its not clear if 
```yaml
general:
    lresume: True
```
needs to be set to restart specific components in a setup. 

**To Reproduce**
Follow the steps above.

**Expected behavior**
Restart any component I want within any setup I want in a clear way.

Thanks a lot for help,
Chris

**System (please complete the following information):**
 - Supercomputer: mistral
- runscript: /pf/a/a270073/esm/runscripts/awicm_recom_esm-piControl-spinup_run.yaml
<details>
<summary>esm_versions check</summary>

```
esm_analysis
├─ version: 0.3.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_archiving
├─ version: 0.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_calendar
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_database
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_environment
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_master
├─ version: 5.1.2
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_master
├─ branch: release
└─ tags: v5.1.2-1-gf5196ac

esm_motd
├─ version: 5.0.2
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_parser
├─ version: 5.1.5
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_plugin_manager
├─ version: 5.0.1
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_profile
├─ version: 5.0.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_rcfile
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/.local/lib/python3.6/site-packages
├─ branch: 
└─ tags: 

esm_runscripts
├─ version: 5.1.22
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts
├─ branch: release
└─ tags: v5.1.22

esm_tools
├─ version: 5.1.0
├─ path: /mnt/lustre01/pf/a/a270073/esm/esm_tools
├─ branch: awicm_recom
└─ tags: v5.0.17-64-g2e1b74d-dirty

esm_version_checker
├─ version: 5.1.4
├─ path: /mnt/lustre01/pf/a/a270073/esm/src/esm_version_checker
├─ branch: release
└─ tags: v5.1.4
```
</details>

**Comment by pgierz** [comment]
Please try with the branch `awicm_recom_paul` and let me know if it works.

**Comment by pgierz** [comment]
Note, I would try myself, but until we have "user independent" run scripts, that would take a bit of time....

**Comment by denizural** [comment]
I solved this issue (in a bit ugly way) by adding

```yaml
general:
  ini_parent_dir: "/some/directory/on/mistral"
  ini_parent_exp_id: test
  ini_parent_date: "2685-12-31"
```

and adding 

```yaml
ini_parent_dir: "${general.ini_parent_dir}"
ini_parent_exp_id: "${general.ini_parent_exp_id}"
ini_parent_date: "${general.ini_parent_date}"
```
under each model section in the runscript (eg. echam, fesom, recom, oasis, jsbach, hdmodel)

**Comment by chrisdane** [comment]
@pgierz:
```
git fetch
git checkout awicm_recom_paul
esm_runscripts awicm_recom_esm-piControl-spinup_run.yaml --verbose --open-run -e esm-piControl_2685 -c
========================================================================
::: Executing the step:  assemble    (step [12/22] of the job:  compute)
========================================================================
Renaming sources to targets for filetype ignore in model jsbach
2021-07-12 14:05:43.937857
Traceback (most recent call last):
  File "/pf/a/a270073/.local/bin/esm_runscripts", line 11, in <module>
    load_entry_point('esm-runscripts', 'console_scripts', 'esm_runscripts')()
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/cli.py", line 225, in main
    Setup()
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/sim_objects.py", line 55, in __call__
    self.compute(*args, **kwargs)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/sim_objects.py", line 89, in compute
    self.config = compute.run_job(self.config)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/compute.py", line 34, in run_job
    config = evaluate(config, "compute", "compute_recipe")
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/helpers.py", line 101, in evaluate
    framework_recipe, framework_plugins, config
  File "/pf/a/a270073/.local/lib/python3.6/site-packages/esm_plugin_manager/esm_plugin_manager.py", line 138, in work_through_recipe
    config = getattr(submodule, workitem)(config)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/filelists.py", line 846, in assemble
    config = complete_targets(config)
  File "/mnt/lustre01/pf/a/a270073/esm/src/esm_runscripts/esm_runscripts/filelists.py", line 134, in complete_targets
    config[model][filetype + "_sources"][categ]
  File "/sw/rhel6-x64/conda/anaconda3-bleeding_edge/lib/python3.6/posixpath.py", line 146, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not dict
Exiting entire Python process!
```

@denizural 
It must be 
```yaml
<model>:
     ini_parent_dir: "${general.ini_parent_dir}/<model>"
```
instead of 
```yaml
<model>:
    ini_parent_dir: "${general.ini_parent_dir}"
```
and the same date issue remains:
```
- missing source: /work/ba1103/a270094/awiesm/test/restart/fesom/fesom.26851231.oce.nc
```
The restart file only has the year, not month and day in it.

I dont understand this. Am I the first person doing a fesom restart with the esm tools? Oo

**Comment by pgierz** [comment]
Short answer: yes, probably. At least for coupled, and only trying to restart part of the model.

**Comment by chrisdane** [comment]
@pgierz: when I cherry-pick your changes, it works -_-

@mandresm: pauls [3b7c824](https://github.com/esm-tools/esm_tools/commit/3b7c824bab65fbc5f5a377dd2bbaeaea805555dc) must go into release. With the current version its impossible to restart fesom. *slowly but surely going crazy*

**Comment by pgierz** [comment]
Be happy it's only slowly ;-)

**Comment by mandresm** [comment]
I think what Paul did in 3b7c824 was to revert back one change that was made to make daily restarts (for fast testing) with FESOM in ESM-Tools possible. This was done 1 year ago during the implementation of `fesom-recom-1.4`. This change, if implemented in release, has the potential to break things for `fesom-recom-1.4`.

Of course I'm not against it, it's more like a warning that we might fix it for someone and break it for someone else. 

@chrisdane , you are absolutely right about the restart cookbook, it's wrong. I've done restarts myself though with AWICM and they worked well. It seems that the restart files for fesom in your parent experiment have the naming convention `fesom.<Year>.<var>.nc` instead of what one would expect from the current configuration previous to Paul's edit, for which the files name would be `fesom.<YearMonthDay>.<var>.nc`. Was the parent experiment run with a recent version of ESM-Tools? If not, and you still wanted to restart using an old name convention you could have always defined in your runscript the following:

```
fesom:
    choose_general.run_number:
        1:        # Changes the naming convention for fesom restarts only for the first run
             restart_in_sources:
                oce_diag: fesom.${parent_date!syear}.oce.diag.nc
                oce_restart: fesom.${parent_date!syear}.oce.nc
                ice_restart: fesom.${parent_date!syear}.ice.nc
```

**Comment by chrisdane** [comment]
Thanks for the tip @mandresm. Yes, I need to restart from old files. But then there should be "one" way of doing this?

Unfortunately I need to reopen: the run was successful but fesom didnt restart:
```
/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/esm-piControl_2685_1m/scripts/esm-piControl_2685_1m_compute_26860101-26860131_31058948.log
576:  clock initialized at time   0.0000000E+00           1        2686
```
Its also visible in the data.

```
runscript: /pf/a/a270073/esm/runscripts/awicm_recom_esm-piControl-spinup_run.yaml
work: /work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/esm-piControl_2685_1m
esm_tools: /pf/a/a270073/esm/esm_tools # still with pauls solution and not miguels
``` 

Thanks for help!

**Comment by mandresm** [comment]
> Thanks for the tip @mandresm. Yes, I need to restart from old files. But then there should be "one" way of doing this?

There are two ways of doing this:
1. add the lines I wrote in the previous post to the runscript
2. or inside the parent expertiment, make a link to the original restarts using the new name convention

**Comment by mandresm** [comment]
About things not working for the restart, could it be a problem with the `first_initial_year` definition?

If you look at these lines in the `fesom.yaml` file you'll notice that this variable probably needs to be the initial date of the parent experiment:
```
choose_lresume:
        false:
                [ .. ]
        true:
                [ ... ]
                choose_general.run_number:
                        # MAM: If it is a restart triggered from a runscript
                        # it is necessary to specify the year of the initial
                        # date of the experiment that is to be continued
                        1:  
                                add_namelist_changes:
                                        namelist.config:
                                                clockinit:
                                                        yearnew: "${first_initial_year}"
```

**Comment by chrisdane** [comment]
The generated fesom.clock
```
/work/ba1103/a270073/out/awicm-1.0-recom/awi-esm-1-1-lr_kh800/esm-piControl_2685_1m/run_26860101-26860131/work/fesom.clock
   84600.0000000000               31        2686
   86400.0000000000               31        2686
```
should actually be
```
   84600.0000000000               365        2685
   0.00000000000000               1          2686
```
The namelist.config entry looks ok:
```
&clockinit
    timenew = 0.0
    daynew = 1
    yearnew = 2686
/
```
Dont know why the clock file is not correct :( For the restart case, its
```
 - "<--append-- ${lasttime} ${parent_date!sdoy} ${parent_date!syear}"
 - "<--append-- ${starttime} ${startday} ${start_date!syear}"
```
It seems that instead of `${parent_date!sdoy}`, which should be 365, rather `${parent_date!day}`, 31, is used. Also, the parent year is wrong. Where/how is `parent_date` defined? I have `ini_parent_date: "2685-12-31"` in the runscript. Its not clear if `parent_date = ini_parent_date`, also not with the help of the docu.

Thanks

**Comment by chrisdane** [comment]
I think I get it. @mandresm, you wrote in your comment that
```
# MAM: If it is a restart triggered from a runscript
# it is necessary to specify the year of the initial
# date of the experiment that is to be continued
```
I think this is not correct or I misunderstand. The condition must rather be `namelist.config:&clockinit:yearnew != first_initial_year`.

When I set 
```
choose_lresume:
        true:
                choose_general.run_number:
                        1:
                                add_namelist_changes:
                                        namelist.config:
                                                clockinit:
                                                        yearnew: "$(( ${first_initial_year} - 1))"
```
fesom considers the run as a restart run:
```
576:  clock initialized at time   0.0000000E+00           1        2686
576:  THIS RUN IS A RESTART RUN!
```
since 
```
https://gitlab.dkrz.de/modular_esm/fesom-1.4/-/blob/master/fesom_cpl/gen_modules_clock.F90#L94
   if(yearnew==yearstart .and. daynew==daystart .and. timenew==timestart) then
       r_restart=.false.
       yearold=yearnew-1 !required for checking if create new output files
    else
       r_restart=.true.
    end if
```
i.e. `yearnew` and `yearstart` must differ to get a restart (since most often daynew=daystart=1 and timenew=timestart=0).
