### ISSUE TITLE
Monthly/Yearly restarts with AWIESM-2.1

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#40]
Hello,

we are having problems running AWIESM-2.1 (which is AWI-CM2 with dynamic vegetation turned on) with yearly restarts. The simulation reaches 1st Feb, hangs, and eventually exists with a wall clock timeout.

A run with monthly restarts works normally.

## Paths
Monthly run is here:
`/work/ollie/stepanek/esm-experiments_v4/myinitialtest/`
Yearly run is here:
`/work/ollie/abose/esm-experiments/myinitialtest/`
A copy of the yearly run has been placed here, in case the master's student running the job cleans up:
`/work/ollie/stepanek/esm-experiments_v4/myinitialtest_failed_abose`

## Versions:
For the monthly run, the following versions were used:
```
You are using the following esm_tools versions:
-----------------------------------------------
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 4.0.1
esm_database : 4.0.0
esm_environment : 4.0.1
esm_master : 4.0.2
esm_parser : 4.0.2
esm_profile : 4.0.0
esm_rcfile : 4.0.0
esm_runscripts : 4.0.3
esm_tools : 4.0.9
esm_plugin_manager : 4.0.1
esm_version_checker : 4.0.2
```

## Namelist differences:
`namcouple`:
```diff                                                                                                                                                                                                    
--- /work/ollie/stepanek/esm-experiments_v4/myinitialtest/run_20000101-20000131/work/namcouple  2020-06-03 08:58:00.000000000 +0200
+++ /work/ollie/abose/esm-experiments/myinitialtest/run_20000101-20001231/work/namcouple        2020-06-02 19:07:20.000000000 +0200
@@ -6,7 +6,7 @@
             2 fesom echam6
  $END
  $RUNTIME
-           2678400
+           31622400
  $END
  $NLOGPRT
            1

```

`namelist.echam`:
```diff
--- /work/ollie/stepanek/esm-experiments_v4/myinitialtest/run_20000101-20000131/work/namelist.echam     2020-06-03 08:58:00.000000000 +0200
+++ /work/ollie/abose/esm-experiments/myinitialtest/run_20000101-20001231/work/namelist.echam   2020-06-02 19:07:20.000000000 +0200
@@ -1,10 +1,10 @@
 &runctl
     dt_start = 2000, 1, 1
-    dt_stop = 2000, 2, 1
+    dt_stop = 2001, 1, 1
     putrerun = 1, 'months', 'first', 0
     lfractional_mask = .false.
     lresume = .false.
-    out_datapath = '/work/ollie/stepanek/esm-experiments_v4//myinitialtest/run_20000101-20000131/work/'
+    out_datapath = '/work/ollie/abose/esm-experiments//myinitialtest/run_20000101-20001231/work/'
     out_expname = 'myinitialtest'
     rerun_filetype = 4
     delta_time = 450

```

`namelist.config`:
```diff
--- /work/ollie/stepanek/esm-experiments_v4/myinitialtest/run_20000101-20000131/work/namelist.config    2020-06-03 08:58:00.000000000 +0200
+++ /work/ollie/abose/esm-experiments/myinitialtest/run_20000101-20001231/work/namelist.config  2020-06-02 19:07:20.000000000 +0200
@@ -5,7 +5,7 @@
 &timestep
     step_per_day = 48
     run_length = 1
-    run_length_unit = 'm'
+    run_length_unit = 'y'
 /
 
 &clockinit
@@ -20,7 +20,7 @@
     climatedatapath = '/work/ollie/pool/FESOM//hydrography/'
     forcingdatapath = ''
     tideforcingpath = ''
-    resultpath = '/work/ollie/stepanek/esm-experiments_v4//myinitialtest/run_20000101-20000131/work/'
+    resultpath = '/work/ollie/abose/esm-experiments//myinitialtest/run_20000101-20001231/work/'
 /
 
 &initialization
@@ -31,10 +31,10 @@
 &inout
     restartflag = 'last'
     output_length = 1
-    output_length_unit = 'm'
+    output_length_unit = 'y'
     output_offset = 64
     restart_length = 1
-    restart_length_unit = 'm'
+    restart_length_unit = 'y'
     restart_offset = 64
     logfile_outfreq = 100
     use_means = .false.

```

## Error Reproducibility
Both models are installed via:
```
$ esm_master install-awiesm-2.1
```

Thereafter, the runscripts can be used found in the `scripts` folder of each of the experiments.

## Some Useful Stuff
Here's a little function to open two namelists of these experiments in vimdiff:
```
function nml_compare() { nmlfile=$1; vimdiff /work/ollie/stepanek/esm-experiments_v4/myinitialtest/run_20000101-20000131/work/$nmlfile /work/ollie/abose/esm-experiments/myinitialtest/run_20000101-20001231/work/$nmlfile }
```

**Comment by pgierz** [comment]
This is a "user error", the `namelist.echam` was configured to write restarts only once at the end of the first month. 

To fix this problem, add the following section to your YAML file, which serves as your runscript:

```yaml
echam:
        restart_rate: 1
        restart_unit: "years"
```

In total, my run configuration looks like this:
```yaml
general:
    setup_name: "awicm"
    compute_time: "01:15:00"
    initial_date: "2000-01-01"
    final_date: "2010-12-31"
    base_dir: "/work/ollie/pgierz/AWIESM_2_1_LR/"
    nmonth: 0
    nyear: 1

awicm:
    version: "2.0"
    postprocessing: false
    scenario: "PALEO"
    model_dir: "/work/ollie/pgierz/AWIESM_2_1_LR/model_sources/awiesm-2.1/"

echam:
        restart_rate: 1
        restart_unit: "years"

jsbach:
        namelist_changes:
                namelist.jsbach:
                        jsbach_ctl:
                                use_dynveg: True
fesom:
    version: "2.0"
    res: "CORE2"
    pool_dir: "/work/ollie/pool/FESOM/"
    mesh_dir: "/work/ollie/dsidoren/input/fesom2.0/meshes/mesh_CORE2_finaltopo_mean/"
    restart_rate: 1
    restart_unit: "y"
    restart_first: 1
    lresume: 0
```

Please note that a "paleo-friendly" yaml configuration using `awiesm` is in preparation.
