### ISSUE TITLE
FESOM2 namelist outdate

### ISSUE THREAD

**Issue by PengyangSong** [esm-tools/esm_tools#414]
Dear developers,
I am trying the ESM_tools (version5), and I want to ask how to solve the outdated namelist source in ESM_tools.

I get some errors like this:

```

MISSING FILES:

- missing source: somepath
- missing target: opbndpath (from namelist.config in FESOM)
2021-07-29 17:28:15.017493

- missing source: somepath
- missing target: tideforcingpath (from namelist.config in FESOM)
2021-07-29 17:28:15.017571

```

 The opbndpath and tideforcingpath is not in FESOM2. My yaml file looks like this:

```
general:
        setup_name: fesom
        compute_time: "01:00:00"
        initial_date: '1948-01-01'
        final_date: '1948-12-31'
        base_dir: "/work/ollie/psong/FESOM2/"
        nyear: 1
        nmonth: 0


fesom:
        version: 2.1
        model_dir: "/home/ollie/psong/esm_tools/fesom-2.1/"
        pool_dir: "/work/ollie/pool/FESOM/"
        mesh_dir: "/work/ollie/psong/mesh_fesom2.0/core2_meanz/"
        res: CORE2
        lresume: 0
        restart_rate: 1
        restart_first: 1
        restart_unit: 'y'
        post_processing: 0
        namelist_dir: "/home/ollie/psong/esm_tools/fesom-2.1/config_notide/"
        add_config_sources:
                cvmix:   "${namelist_dir}/namelist.cvmix"
                icepack: "${namelist_dir}/namelist.icepack"
        remove_namelist_changes: [namelist.diag]
```

also the namelist.diag is outdated

**Comment by pgierz** [comment]
Hey @PengyangSong  can you put your code in triple backticks? Then it will be nicely formatted so we can read it more easily. 

@denizural this looks a lot like the problem you solved. @PengyangSong, what version are you on? I would recommend updating everything, I think we already fixed this one.

**Comment by PengyangSong** [comment]
@pgierz Thanks! I confused backticks with quote marks :-(
I am switching to FESOM2.1 (official release).

**Comment by pgierz** [comment]
It's this one: `
Sometimes, it makes the regular one: '

Fesom 2.1 is not yet really all the way supported. It's on our radar though.

**Comment by mandresm** [comment]
I'm currently working on it and try it to coordinate it with different groups. These different groups are using fesom-2.1 everywhere under fesom-2.0.yaml so I'm trying to put together a nice fesom-2.1.yaml before chaos takes over. I would recommend at this point @PengyangSong to wait until next week (I am thinking on having that in `develop`, not in `release`).

**Comment by mandresm** [comment]
And by the way @PengyangSong , I found the exact same problem you are reporting here and it is solved for my branch, but it still needs a lot of extra work.

**Comment by PengyangSong** [comment]
@mandresm thanks, and I would really appreciate if you can keep me updated with your bug fix.

**Comment by mandresm** [comment]
@PengyangSong, this is not a bug fix, this is a new development, fesom 2.1 is not yet supported in ESM-Tools and we won't consider it fully supported until it's merged into release branch  in version 6.0 (happening in the coming weeks). This means I would expect a lot of problems if you decide to go ahead and use fesom-2.1 from ESM-Tools before release 6.0, and I would strongly recommend don't run any important simulation with FESOM-2.1 from ESM-Tools until the release of the new version of ESM-Tools.

**Comment by JanStreffing** [comment]
I recently ran the latest refactoring branch of FESOM2 with esm_tools. The "trick" is that instead of using the namelist templates from the `esm_tools/namelist/fesom2` folder you use:

```
fesom:
    namelist_dir: "${model_dir}/config/"
    add_namelists:
        - namelist.tra
        - namelist.dyn
    add_config_sources:
        tra:     "${namelist_dir}/namelist.tra"
        dyn:     "${namelist_dir}/namelist.dyn"
    add_config_in_work:
        tra:     "namelist.tra"
        dyn:     "namelist.dyn"
    add_config_files:
        tra:     tra
        dyn:     dyn
```

If you run a coupled model, don't forget to add:
```
    add_namelist_changes:
        namelist.tra:
            tracer_phys:
                surf_relax_s: 0.0
```
With this you can run any version of FESOM2 you like, using the namelist templates that come with the FESOM2 source code.

Closing this issue here.
