### ISSUE TITLE
Overlapping workflow jobs in coupled model setup

### ISSUE THREAD

**Issue by ackerlar** [esm-tools/esm_tools#425]
**Describe the bug**
When I run the coupled setup AWIESM + PISM, bash scripts are executed during the couple in and couple out in order to preprocess the data. In my PISM runscript I say that the couple in job shall be run before `precompute`:
```
        workflow:
                next_run_triggered_by: couple_out
                subjobs:
                        couple_in:
                                nproc: 1
                                run_before: prepcompute
                                #script: pseudo_couple_in_pism.sh
                                script: coupling_awiesm2pism.functions
                                script_dir: /pf/a/a270124/esm_tools/runscripts/awicm-pism/coupling/
                                #call_function: call_this
                                call_function: awiesm2pism
                                env_preparation: env_pism.py
                                run_only: first_run_in_chunk
                                #skip_chunk_number: 1
```
Sometimes it happens that the execution of the shell script takes a bit longer. So that the `compute` job already started but the shell script has not yet finished so that some files cannot be found during `compute` and the simulation breaks (`/work/ba0989/a270124/125ka_FINAL_TEST03/`).

Is there are way to start `compute` (or `precompute`) just when the shell scripts have finished or certain conditions are met like certain files are where the need to be?

**To Reproduce**
Use these branches:
 - esm_runscripts (https://github.com/ackerlar/esm_runscripts.git <https://github.com/ackerlar/esm_runscripts.git>)
 - esm_tools (https://github.com/ackerlar/esm_tools.git <https://github.com/ackerlar/esm_tools.git>)
 - esm_parser (https://github.com/esm-tools/esm_parser.git <https://github.com/esm-tools/esm_parser.git>) 

and run a coupled setup, e.g. `esm_tools/runscripts/awicm-pism/awicm-pism_125ka.yaml`

**System (please complete the following information):**
 - Supercomputer: `mistral`
 - Version:
 ```
+---------------------+-------------+---------------------------------------------------------------+-------------------+---------------------------+
| package_name        | version     | file                                                          | branch            | tags                      |
|---------------------+-------------+---------------------------------------------------------------+-------------------+---------------------------|
| esm_calendar        | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_database        | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_environment     | 5.1.1       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_master          | 5.1.3       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_motd            | 5.0.2       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_parser          | 5.1.7       | /mnt/lustre01/pf/a/a270124/esm_parser                         | prep_release      | v5.1.7-17-g333f8ec        |
| esm_pism            | 0.0.1.dev15 | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages | main              | Error                     |
| esm_plugin_manager  | 5.0.1       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_profile         | 5.0.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_rcfile          | 5.1.0       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
| esm_runscripts      | 5.0.14      | /mnt/lustre01/pf/a/a270124/esm_runscripts                     | prep_release      | v5.0.14-63-gfceedc4       |
| esm_tools           | 5.1.17      | /mnt/lustre01/pf/a/a270124/esm_tools                          | prep_release_wiso | v5.1.17-79-gfd79146-dirty |
| esm_version_checker | 5.1.5       | /mnt/lustre01/pf/a/a270124/.local/lib/python3.6/site-packages |                   |                           |
+---------------------+-------------+---------------------------------------------------------------+-------------------+---------------------------+
```
