### ISSUE TITLE
Numbering of waminfo file

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#486]
@mandresm and I found that the OpenIFS Wave model restart control file waminfo is tagged with a date when copied to the restart file folder. We could not see a reason as to why. This made some trouble for  @mathanase in an edge case, using an OpenIFS restart that was not made with esm_tools.

Issue is low prio.

**Comment by mandresm** [comment]
There was actually a reason for that:

Let's say you are doing a branch off experiment, and you want to restart at some point that is not the final leg of your experiment. Then you setup the correct restart dates in your runscript for restarting, and ESM-Tools automatically gets the correct oifs restart files for you, except the `waminfo` file, in which case it gets the last one. I am not 100% sure that the modifications in the `preprocessing` scripts applied to the wamfile are actually enough to avoid a problem that would be rather difficult to debug.

**Comment by mandresm** [comment]
@mathanase , I know we found a solution for this problem through out the runscript. Can you provide the solution?

Also, can you describe what the problem was a bit more in detail? Was the problem for restarting and ESM-Tools ksh simulation?

**Comment by mathanase** [comment]
The problem was that with ESM-Tools, oifs restart folders are organised such as:
`/parent_exp_folder/restart/oifs/yyyymmdd/`
Where `yyyymmdd` is the last date of a given leg.

With the ksh-scripts, the folder structure was slightly different, such as:
`/parent_exp_folder/restart/oifs/leg_number/`
Where `leg_number` can go from 00001 to 99999. 

 
The solution is to add the following lines in the ESM-runscript:

```
oifs:
   prev_run_config_file: "/path/to/homemade_config_file/oifs_prevrun_config.yaml"
   namelist_changes:
        fort.4:
            NAMDIM:
                    NPROMA: -8
    choose_general.run_number:
        1:
            in_date_folder: "00009"        # Number of parent exp leg chosen to branchoff from
            add_restart_in_sources:
                waminfo: "${in_date_folder}/waminfo"
```

In the above, the file oifs_prevrun_config.yaml is such as:

```
oifs:
        filebase_wam_work: "20091231000000_"  # Last date of the previous leg's previous leg
        branchoff: false
        next_ndays: 1827             # N days in the previous leg's previous leg.
                                     # Both info can be found in the previous leg's restart folder
 
general:
        start_date: "2010-01-01"               # Start date of previous leg
        end_date: "2014-12-31"                 # End dare of previous leg

```
