### ISSUE TITLE
Suggestion to rename input_in_work and input_files to make functionality obvious from name

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#488]
Here is another small issue I stumbled over in my experiment of implementing a new setup with minimal esm_tools developer help. I forgot to add `input_files` in the following code block, because I thought I only need to give one list of files and one list of sources:

```
input_in_work:
        sst_forcing: "comb_input4MIPs_SSTsAndSeaIce_PAMIP_pdSST_pdSIC_gn.nc"
        sic_forcing: "comb_input4MIPs_SSTsAndSeaIce_PAMIP_pdSST_pdSIC_gn.nc"

input_files:
        sst_forcing: sst_forcing
        sic_forcing: sic_forcing

input_sources:
        sst_forcing: "${input_dir}/comb_input4MIPs_SSTsAndSeaIce_PAMIP_pdSST_pdSIC_gn.nc"
        sic_forcing: "${input_dir}/comb_input4MIPs_SSTsAndSeaIce_PAMIP_pdSST_pdSIC_gn.nc"
```

After talking to Miguel, I understand that `input_in_work` and `input_sources` are lists of all potential input files & sorces, and that some of these are optional. e.g. When running CMIP scenarios we have all scenario forcing files here, even the ones that we don't use. `input_files` on the other hand is the list of actual input files for this particular run. So all three are needed.

To me this distinction was not obvious from the names. To facilitate usability I suggest renaming them to something like:
`input_in_work` -> `all_possible_input_files`
`input_files` -> `actual_input_files`
`input_source` -> `all_possible_input_file_sources`

When renaming you would likely have to run a script of all config and runscript files to ensure it's renames everywhere.
