### ISSUE TITLE
Variables in nested choose blocks cannot be changed from runscript

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#501]
**Describe the bug**
Variables in nested choose blocks in e.g. component yamls cannot be changed directly in the runscript. Example
I'd like to change the variable `global_tag` in nemo.yaml (with the relevant parts extracted).
nemo.yaml:
```yaml
global_tag: ""
choose_lresume:
        true:
                nn_msh: 0
                choose_general.run_number:
                        1:
                                global_tag: "_global"
```
runscript:
```yaml
nemo:
   global_tag: "_funny_new_tag"
```
the variable `nn_msh: 0` can be changed from the runscript while `global_tag` does not work
**To Reproduce**
Steps to reproduce the behavior: Use `runscripts/foci/foci-restart-scenario_run.yaml` and try to set `global_tag: "_funny_new_tag"`

**Expected behavior**
In the final namelist or finished config we should see `global_tag: "_funny_new_tag"` and not `global_tag: "_global"`.
A workaround is to use
```yaml
choose_lresume:
     true:
       choose_general.run_number:
          1:
             global_tag: "_funny_new_tag"
```
in the runscript yaml.
**System (please complete the following information):**
 - all
 - latest

**Comment by seb-wahl** [comment]
You are both right and wrong, Miguel:
if I use `global_tag: "this_is_funny"` it works as expected. If I try to set `global_tag: "" ` it does not. So it looks like the parser does not like to set the default value (which is `""`) for `global_tag`. However it works if I use 
```
choose_lresume:
     true:
       choose_general.run_number:
          1:
             global_tag: ""
 ```
