### ISSUE TITLE
Fix Reusable Action in CI

### ISSUE THREAD

**Issue by pgierz** [esm-tools/esm_tools#508]
In the reusable workflows in the CI system, we specify a certain branch from which the action template is taken:

```
uses: esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@monorepo_ci_test
```

In context, that looks like this:

```yaml
jobs:
    compile-ollie:
        name: Compile Test AWIESM (Ollie)
        # Pattern for uses: github-org/repo/some/path/in/repo@commit_or_branch
        # (if @commit_or_branch is omitted, it assumes the default)
        uses: esm-tools/esm_tools/.github/workflows/esm_tools_actions_hpc_awi_ollie.yml@monorepo_ci_test
        secrets:
          dkrz-token: ${{ secrets.GITLAB_DKRZ_TOKEN }}
          awi-token: ${{ secrets.GITLAB_AWI_TOKEN }}
        with:
          model_name: awiesm
          # versions to test as a space seperated list
          model_version: "2.1 2.1-wiso 2.1-recom"
```

After the merge, this will need to be moved to the release branch, or perhaps a tagged version.
