### ISSUE TITLE
fesom.clock created with current rather than last run timestep

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#510]
**Describe the bug**
When restarting a FESOM (1 or 2) simulation, the esm_tools are generating a fesom.clock file based on the current simulation timestep. The correct behavior would be to either
a) generate the fesom.clock file based on the previous simulations timestep or
b) use the fesom.clock from the previous simulation.

As a result the FESOM2 does not start up after reading the restart files:
```
96:  restart/ times are:   31535760.0000000        31535640.0000000
96:  the model will stop!
```

**To Reproduce**
on juwels as part of chhb19 project:
```
cd esm_tools
git checkout awicm-3-frontiers-xios
cd model_codes
esm_master install-awicm-3-frontiers-xios
cd esm_tools/runscripts/awicm3/frontiers
esm_runscripts awicm3-frontiers-xios-juwels-TCO319L137-DART.yaml -e fesom_restart_error
```

**Expected behavior**
The simulation starts up

**System (please complete the following information):**
 - Supercomputer: juwels

```
+---------------------+-----------+---------------------------------------------------------------------+------------------------+-----------------------------+
| package_name        | version   | file                                                                | branch                 | tags                        |
|---------------------+-----------+---------------------------------------------------------------------+------------------------+-----------------------------|
| esm_calendar        | 5.0.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_database        | 5.0.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_environment     | 5.1.3     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_master          | 5.1.6     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_motd            | 5.0.2     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_parser          | 5.1.12    | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_plugin_manager  | 5.0.1     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_profile         | 5.0.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_rcfile          | 5.1.0     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_runscripts      | 5.1.37    | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
| esm_tools           | 5.0.12    | /p/project/chhb19/jstreffi/esm_tools                                | awicm-3-frontiers-xios | v5.0.12-437-g60b072c4-dirty |
| esm_version_checker | 5.1.5     | /p/home/jusers/streffing1/juwels/.local/lib/python3.6/site-packages |                        |                             |
+---------------------+-----------+---------------------------------------------------------------------+------------------------+-----------------------------+

```

@koldunovn @mandresm @tsemmler05 @pgierz

**Comment by mandresm** [comment]
Hi @JanStreffing,

Can you try this?:
```
fesom:
    ini_parent_date: "${prev_date}"
```

**Comment by JanStreffing** [comment]
Does this work with simulations where the FESOM2 standalone spinup run was not made with esm_tools? 

I'm currently using:

```
    lresume: true
    ini_parent_exp_id: "D00"
    ini_parent_date: "1989-12-31"
    ini_parent_dir: "/proj/awi/input/fesom2/restart/DART/"
    choose_general.run_number:
        1:
            restart_in_sources:
                par_oce_restart: /proj/awi/input/fesom2/restart/DART/fesom.1989.oce.restart/*.nc
                par_ice_restart: /proj/awi/input/fesom2/restart/DART/fesom.1989.ice.restart/*.nc
```

My current timestep is 240s. The timestep of the previous simulation was 360s. In my fesom.clock i get
`86160 365 1989` but i want `86040 365 1989` 
I just tired it with  `ini_parent_date: "1989-12-31T23:54:00"` but saw no change. Still 86160

**Comment by mandresm** [comment]
Hi @JanStreffing ,

My bad... look at this:
```
lasttime: "$(( 86400 - ${time_step}))"
currentday: "${current_date!sdoy}"
choose_currentday:
        "1":
                starttime: "0.0000000000000"
                startday: 1
        '*':
                starttime: "86400.0000000000"
                startday: "$(( ${start_date!sdoy} - 1 ))"

choose_lresume:
        false:
                create_config:
                        fesom.clock:
                                - "<--append-- 0.0000000000000 ${initial_date!sdoy} ${initial_date!syear}"
                                - "<--append-- 0.0000000000000 ${initial_date!sdoy} ${initial_date!syear}"
        true:
                create_config:
                        fesom.clock:
                                - "<--append-- ${lasttime} ${parent_date!sdoy} ${parent_date!syear}"
                                - "<--append-- ${starttime} ${startday} ${start_date!syear}"
```

FESOM restart had worked before for old ksh experiments probably because they were run with the same step. In this particular case, you want to manually define `lasttime` inside your `choose_general.run_number`:
```
choose_general.run_number:
        1:
                lasttime: "1989-12-31T23:54:00"
```
