### ISSUE TITLE
Modification of XML files from within esm_tools yaml files

### ISSUE THREAD

**Issue by JanStreffing** [esm-tools/esm_tools#511]
**Is your feature request related to a problem? Please describe.**
We are starting to use AWI-CM3 with the XIOS IO server. The output is no longer configured in f90 namelist files, but in xml files. It would be nice to be able to modify the xml files from within esm_tools, so as to not have to make new xml template files for every small change.

**Describe the solution you'd like**
Something that looks like for fortran namelist changes would be nice:
```
        add_namelist_changes:
                fort.4:
                        NAMCLDP:
                                SCLCT_SWITCH: 1
```

Do we already have this for FOCI-OpenIFS? Is this on your wishlist @joakimkjellsson 

@denizural
