### ISSUE TITLE
esm_parser fails because of missing fesom destination

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#582]
**Describe the bug**
With fresh install of esm-tools v6 and awiesm-2.1-wiso calling esm_runscript on a pretty standard simulation YAML fails with the following error message:
```
(base) a270061@mlogin108% esm_runscripts test_mixing_noise.yaml -e test_mixing_noise -c
Traceback (most recent call last):
  File "/mnt/lustre01/pf/a/a270061/esm_tools_v6/esm_tools/src/esm_parser/esm_parser.py", line 1892, in recursive_get
    result = config_to_search[this_config]
KeyError: 'destination'
[...]
esm_parser.esm_parser.EsmParserError: Sorry, a variable was not resolved: fesom.destination not found
```

**To Reproduce**
See above

**Expected behavior**
Fesom2 should know its destination

**Code change to fix this issue (to be included into esm-tools as a bugfix)**
Add the following line to the fesom-2.0.yaml in esm tools component configurations:
```
destination: fesom-2.0
```
The resulting choose_version block should look like this:
```
choose_version:
  '2.0':
    branch: 2.0.2
    git-repository:
    - https://github.com/FESOM/fesom2.git
    - https://gitlab.dkrz.de/FESOM/fesom2.git
    install_bins: bin/fesom.x
    destination: fesom-2.0
```

**System (please complete the following information):**
 - Supercomputer: mistral
 - Version [Please run `esm_versions check`]
 ```
   (base) a270061@mlogin104% esm_tools --version
esm_tools, version 6.1.8
```
(esm_versions check is not supported anymore!)

**Additional context**
Bugfix has been designed with great help of @pgierz

**Comment by mandresm** [comment]
Hi @christian-stepanek,

> 
> **Additional context** Bugfix has been designed with great help of @pgierz

Does this mean that there is a bugfix for this already?

Otherwise, can you also provide the runscript you are using?

**Comment by mandresm** [comment]
Also please note that it is very important, that if you installed `awiesm-2.1-wiso`, the `general.version` or `awiesm.version` in the runscript needs to be `2.1-wiso`. You will also need to remove all the versions inside the model components:

```
general:
    version: "2.1-wiso"
echam:
    # make sure there is no version variable here, it is controlled by the general version you specified
fesom:
    # make sure there is no version variable here, it is controlled by the general version you specified

**Comment by christian-stepanek** [comment]
@mandresm @pgierz 
No, the bugfix is only local yet, I implemented it in my installation of esm-tools v6.

I think @pgierz wanted to introduce it in the esm-tools repository, but maybe I am mistaken.

The runscript is available at:
```
/home/a/a270061/esm_tools_v6/esm_tools/my_runscripts/test_mixing_noise.yaml
```

**Comment by mandresm** [comment]
Please see the comments on the runscript:

```
awiesm:
    version: "2.1"     # This invokes the standard paleo repository and options, that's why you are getting the destination error, you should use here the same version as in esm_master ("2.1-wiso")

echam:
    with_wiso: False # This variable is by default controlled by the awiesm.version, of course you can set it false if you want, so that's fine


fesom:
    version: "2.0" # You should remove this line, there are special requirements to use the wiso version of fesom that are only triggered from awiesm.version. If you redefine the fesom.version here you won't get those changes
    with_wiso: False
```

**Comment by christian-stepanek** [comment]
> Also please note that it is very important, that if you installed `awiesm-2.1-wiso`, the `general.version` or `awiesm.version` in the runscript needs to be `2.1-wiso`. You will also need to remove all the versions inside the model components:
> 
> ```
> general:
>     version: "2.1-wiso"
> echam:
>     # make sure there is no version variable here, it is controlled by the general version you specified
> fesom:
>     # make sure there is no version variable here, it is controlled by the general version you specified
> ```

Actually, putting there version information 2.1-wiso lead to another issue as a coupling field was then not found. @pgierz knows more about the background. To overcome this issue I have set the settings as follows (see above mentioned yaml for more info if necessary):
```
general:
    setup_name: "awiesm"
awiesm:
    version: "2.1"
echam:
    with_wiso: False
fesom:
    version: "2.0"
    with_wiso: False
```
The version for fesom (2.0) looks quite inconsistent with the other settings, but I was notified by @pgierz that this is the correct setting.

Actually, for my simulation I am not really interested in isotopes. I installed awi-esm2.1-wiso to be up to data with the physics included in that version.

**Comment by mandresm** [comment]
If you remove the versions in all the components, and you only leave the version for `awiesm` the coupling issue should go away.

**Comment by mandresm** [comment]
To deactivate wiso, you need to set `with_wiso: False` in the `general` section once, not in the components (there's a mistake in the `awiesm-2.1.yaml` documentation). There is also an explanation on how to use this different versions and variables at the beginning of the `awisem-2.1.yaml` file. Please, let us know if this documentation needs to be improved.

**Comment by pgierz** [comment]
To make a long story short, on my next AWI-ESM Support Day, I will spent all day going through the example run scripts to make sure it all works...

**Comment by pgierz** [comment]
As the PR relevant to this has been merged in, I will close this issue. @mandresm and I have planned to get in touch with the AWI-ESM users and do sort of "hack-week" to ensure that AWI-ESM (with all the bells and whistles) are easy to use. This shall result in a new version number, `6.2.0`. Version number semantics are a thing I should at some point maybe just give a talk on....

**Comment by christian-stepanek** [comment]
@mandresm @pgierz

With various trials I have found only one way to get esm_runscripts beyond the error message "Coupling var not found:  o18w_oce":
```
general:
    setup_name: "awiesm"
    with_wiso: False
awiesm:
    version: "2.1"
```
No further mentions of any wiso-related settings in submodels.

Though, that leads to lctlib not being found anymore as esm_runscripts is searching for that file at model_codes/awiesm-2.1-wiso_ref/echam-6.3.05p2-concurrent_radiation-paleodyn/lctlib_nlct21.def, but I only have model_codes/awiesm-2.1-wiso_ref/echam-6.3.05p2-wiso/lctlib_nlct21.def. That problem can only be mitigated if one redefines the location of lctlib in the jsbach section, e.g.:
```
jsbach:
    input_sources:
        lctlib: "/home/a/a270061/esm_tools_v6.1.10/model_codes/awiesm-2.1-wiso_ref/echam-6.3.05p2-wiso/lctlib_nlct21.def"
```
or sets
```
awiesm:
    version: "2.1-wiso"
```
Yet, in the latter case the notorious coupling error message reappears.

It seems that the structure of awi-esm-2.1-wiso is not so similar to that of awi-esm-2.1 that one can just switch-off wiso in awi-esm-2.1-wiso and expect everything to run out of the box. If I am not mistaken this has worked in the past. Please correct me if I am wrong.

Why is this of relevance? If I want to be sure that I am always up-to-date with physics as employed in the awi-esm-2.1-wiso model, but want to avoid additional computational expense related to wiso-computations (because maybe I am not interested in wiso anyway), then I rather prefer to use "awi-esm-2.1-wiso without wiso" instead of "awi-esm-2.1" - reason is that in general I cannot take it for granted that both versions will always be identical, with the obvious exception of wiso-related code, am I right?

**Comment by mandresm** [comment]
Hi @christian-stepanek ,

I cannot reproduce the `Coupling var not found: o18w_oce` issue with the following configuration on my runscript:
```
general:
    setup_name: "awiesm"
    with_wiso: False
awiesm:
    version: "2.1-wiso"
```

Would you provide the path to the runscript so that I can try to reproduce the error?
