### ISSUE TITLE
esm-tools are sensitive to use of spaces or tabs in the yaml configuration

### ISSUE THREAD

**Issue by christian-stepanek** [esm-tools/esm_tools#59]
**Description of the problem**
If simulation yaml-files (that replace the traditional run scripts) are modified by hand, the user may fall into the trap to use tabs for aligning the yaml lines while he/she would be supposed to use spaces to this end.

If a tab is employed to align lines in the yaml-file instead of spaces, that leads yaml files that look absolutely correct by eye if displayed in traditional editors. Yet, the call to esm_runscripts will fail with error messages that are not obviously pointing to incorrect usage of tabs vs. spaces:

```
stepanek@ollie0:~/esm-tools_v4/esm_tools/myrunscripts$ esm_runscripts myinitialtest_yearly.yaml -e myinitialtest_yearly -c -U
Started from:  /home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts
starting :  compute
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 1: general:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 4: general:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 5: setup_name:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 6: compute_time:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 7: initial_date:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 8: final_date:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 9: base_dir:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 10: nmonth:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 11: nyear:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 13: awicm:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 14: version:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 15: postprocessing:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 16: scenario:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 17: model_dir:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 19: echam:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 20: restart_rate:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 21: restart_unit:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 22: disturbance_years:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 24: jsbach:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 25: namelist_changes:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 26: namelist.jsbach:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 27: jsbach_ctl:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 28: use_dynveg:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 29: fesom:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 30: version:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 31: res:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 32: pool_dir:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 33: mesh_dir:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 34: restart_rate:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 35: restart_unit:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 36: restart_first:: command not found
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/cleaned_runscript: line 37: lresume:: command not found
```
The culprit is line 19 (disturbance_years: [ 2013 ]) of the runscript,
```
general:
    setup_name: "awicm"
    compute_time: "01:30:00"
    initial_date: "2000-01-01"
    final_date: "2099-12-31"
    base_dir: "/work/ollie/stepanek/esm-experiments_v4/"
    nmonth: 0
    nyear: 1

awicm:
    version: "2.0"
    postprocessing: false
    scenario: "PALEO"
    model_dir: "/home/ollie/stepanek/esm-tools_v4/model_codes/awiesm-2.1/"

echam:
        restart_rate: 1
        restart_unit: "years"
        disturbance_years: [ 2013 ]

jsbach:
        namelist_changes:
                namelist.jsbach:
                        jsbach_ctl:
                                use_dynveg: True
fesom:
    version: "2.0"
    res: "CORE2"
    pool_dir: "/work/ollie/pool/FESOM/"
    mesh_dir: "/work/ollie/dsidoren/input/fesom2.0/meshes/mesh_CORE2_finaltopo_mean/"
    restart_rate: 1
    restart_unit: "y"
    restart_first: 1
    lresume: 0
```
where by accident a tab was used to align the text. After resolving this issue the simulation can be submitted without any error.

While this may appear to the expert to be an epiphany, I already can foresee the frustration of many esm-tools users, that are less experienced in YAML-/Python-Syntax, when getting stuck with difficult to interpret errors while submitting simulations whose YAML-files are syntactically correct by eye.

**Suggested solution:**
There are various steps that I think are necessary to avoid confusion on the user side:
- add a comment to any yaml-file / yaml-template that is distributed with the esm tools that explains the need to exclusively use spaces to align lines (such a comment could also highlight that alignment is mandatory, see my note 1) at the end of this issue report)
- as above, add the same kind of information to any YAML-related documentation of the ESM-tools.
- as a last resort, add functionality to esm_runscripts that either drops an error message and cleanly exits if tabs are detected in the YAML-file, or automatically replaces tabs by spaces (if this is possible)

**employed run script (on Ollie):**
/home/ollie/stepanek/esm-tools_v4/esm_tools/myrunscripts/myinitialtest_yearly.yaml

**employed esm_tools versions:**
esm_archiving : unknown version!
esm_autotests : unknown version!
esm_calendar : 4.0.1
esm_database : 4.0.0
esm_environment : 4.0.1
esm_master : 4.0.2
esm_parser : 4.0.2
esm_profile : 4.0.0
esm_rcfile : 4.0.0
esm_runscripts : 4.0.3
esm_tools : 4.0.9
esm_plugin_manager : 4.0.1
esm_version_checker : 4.0.2

**Note 1)**
The culprit here is IMHO the oversensitivity of python and YAML towards the way lines are to be aligned in a file. While the developers of said languages certainly had good intentions when demanding YAML and python interpreters to be strict with regard to line alignment, and felt high-spirited enough to replace "end"-statements, that are common features of other languages, by a specific amount of "empty space" at the beginning of a line, one has to also state that their decision has wide-ranging implications. In some specific cases (as here), the "empty-spaces"-design has in my opinion rather the characteristic of a bug than of a feature.
