### ISSUE TITLE
Order of choose blocks matters in machine.yaml

### ISSUE THREAD

**Issue by seb-wahl** [esm-tools/esm_tools#624]
**Describe the bug**
I'm pretty sure this is a bug and not a feature: If I place the `choose_compiler_mpi:` block
```yaml
choose_compiler_mpi:
....
....
choose_iolibraries:
....
....
```
block in e.g. `blogin.yaml` **AFTER** the `choose_iolibraries` block such as
```yaml
choose_iolibraries:
....
....
choose_compiler_mpi:
...
...
```
the `add_module_actions` and `add_export_vars` from the 
```yaml
choose_compiler_mpi:
....
....
```
block are not used. This really puzzles me as I was always convinced that the order of statements in a yaml file does not matter. 

**To Reproduce**
```bash
esm_master get-foci-default
# modify `machine.yaml` e.g. blogin.yaml as described above
esm_master comp-foci-default/oasis
```
The compilation will crash as the modules for intel and e.g. the `export FC=mpiifort` from the `choose_compiler_mpi:` block  in the shell script that is generated are missing.

**Expected behavior**
The order should not matter, at least to my understanding of yaml syntax and esm_tools

**System (please complete the following information):
tested on blogin and levante

**Comment by pgierz** [comment]
This sounds like an excellent case for writing basic unit tests...

My understanding is as follows: yaml ends up in a Python (unordered) dictionary. You can force it to be an ordered dictionary, but we didn't need that so far (?)

However, the order that the Python interpretation then goes over the dictionary keys to solve the choose blocks (might be?) is then random. So, testable question: does the same failure occur every time? Can you induce a similar failure with made up (non-important) choose blocks?

**Comment by mandresm** [comment]
Just a comment: the order is not random, but the order of reading is difficult to predict if you have many chooses and adds.
 That being said, this is a very bad bug, and one that needs to be look at carefully. I do this kind of stuff very often without problems, so there must be something specific that is triggering the bug.

**Comment by mandresm** [comment]
I think I know what's happening. On one side we have this `choose_compiler_mpi`:

https://github.com/esm-tools/esm_tools/blob/9d2752dd80a584256abfeb791de9f73a77a17494/configs/machines/blogin.yaml#L98-L105

On the other side we have a double nested choose:
https://github.com/esm-tools/esm_tools/blob/9d2752dd80a584256abfeb791de9f73a77a17494/configs/machines/blogin.yaml#L141-L158

The problem here is that there are 2 `choose_compiler_mpi` dictionaries. They "live" okay together without giving a warning because they are nested in two different levels. The problem comes when one is resolved, the other is overwritten. We could solve this by complementarily combining both `choose_compiler_mpi` after the solution of the `choose_iolibraries`. However, when information is repeated, there is no way of knowing which information should get priority, it's a non trivial problem.

Potential long term solution:
- Develop a tree-leave algorithm to identify these problems and throw errors (I've already worked on a design for this type of algorithm, but did not have time to implemented it, this is a very similar problem to that one of the NEMO namelists you experiencedin October).

Short term solution:
- Not beautiful but fast, add `add_` to one of the two `choose_compiler_mpi`. Then you are telling ESM-Tools about the order of resolving and combining the chooses.
- More beautiful: keep chooses separated, and for those things that require both cases to be met, use ESM-Tools variable dependencies:
```yaml
choose_compiler_mpi:
    intel2021_impi2021:
        compiler_mpi_path: intel2021.2_impi2021.2_20211007
        add_module_actions:
             [ ... ]
     intel2019_impi2019:
        compiler_mpi_path: intel2019.0.5_impi2019.5_20200811
        add_module_actions:
             [ ... ]

choose_iolibraries:

    [ ... ]
    geomar_libs:
        add_export_vars:
                IO_LIB_ROOT: /home/shkjocke/sw/HPC_libraries/${compiler_mpi_path}
                PATH: $IO_LIB_ROOT/bin:$PATH
                LD_LIBRARY_PATH: $IO_LIB_ROOT/lib:$LD_LIBRARY_PATH

                SZIPROOT: $IO_LIB_ROOT
                HDF5ROOT: $IO_LIB_ROOT
                HDF5_ROOT: $HDF5ROOT
                NETCDFROOT: $IO_LIB_ROOT
                NETCDFFROOT: $IO_LIB_ROOT
                ECCODESROOT: $IO_LIB_ROOT

                HDF5_C_INCLUDE_DIRECTORIES: $HDF5_ROOT/include
                NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
                NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                NETCDF_CXX_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                OASIS3MCT_FC_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
```

This approach should allow you to change the order.
