### ISSUE TITLE
AWICM3: very slow start of the first run

### ISSUE THREAD

**Issue by shijian0702** [esm-tools/esm_tools#806]
**Describe the problem you are facing**

The awicm3-v3.1 always spends much time to start the first run, dealing with the partial restart files of fesom: over 30 minutes for high-resolution (Tco319-BOLD) and over 20 minutes for low resolution (TCO95-CORE2). For the second run, it just took a few seconds to read the raw restart files. 
As far as I know, other climate models, like awi-esm2, have no similar issue.  I'm not sure whether the problem is from awicm3 or esm_tools. Is it normal or something's wrong with my setup?

**Runscrip and other relevant files**
```
general:
    user: !ENV ${USER}
    setup_name: "awicm3"
    version: "v3.1"
    account: "ab0995"
    compute_time: "08:00:00"
    initial_date: "1850-01-01"
    final_date: "1900-01-01"
    base_dir: "/work/ab0246/${user}/runtime/${general.setup_name}-${general.version}/"
    nday: 0
    nmonth: 0
    nyear: 10

awicm3:
    postprocessing: false
    model_dir: "/home/a/${user}/model_codes/${general.setup_name}-${general.version}/"
    pool_dir: "/work/ab0246/a270092/input/"

fesom:
    resolution: "CORE2"
    pool_dir: "/work/ab0246/a270092/input/fesom2/"
    mesh_dir: "${pool_dir}/core2/"
    restart_rate: 10
    restart_unit: "y"
    restart_first: 1
    lresume: true
    time_step: 2400
    nproc: 384
    ini_parent_exp_id: "D00"
    ini_parent_date: "1849-12-31"
    ini_parent_dir: "/work/ab0246/a270196/input/fesom2/restart/CORE2/"
    choose_general.run_number:
        1:
            restart_in_sources:
                par_oce_restart: /work/ab0246/a270196/input/fesom2/restart/CORE2/fesom.1849.oce.restart.2400/*.nc
                par_ice_restart: /work/ab0246/a270196/input/fesom2/restart/CORE2/fesom.1849.ice.restart.2400/*.nc
    namelist_dir: "/home/a/a270196/runscripts/namelist/spinup/fesom2/"

oifs:
    resolution: "TCO95"
    levels: "L91"
    prepifs_expid: aack
    input_expid: awi3
    wam: true
    lresume: false
    time_step: 3600
    nproc: 384
    omp_num_threads: 8
    add_namelist_changes:
        fort.4:
            NAERAD:
                NSOLARSPECTRUM: "1"
                NCMIPFIXYR: "1990"

rnfmap:
    omp_num_threads: 128

oasis3mct:
    lresume: true # Set to false to generate the rst files for first leg
    time_step: 7200

xios:
    with_model: oifs
    nproc: 8
    omp_num_threads: 16
```
log file of the first run:
[pi_awicm3_tco95_core2_awicm3_compute_18500101-18591231_1074979.log](https://github.com/esm-tools/esm_tools/files/9403282/pi_awicm3_tco95_core2_awicm3_compute_18500101-18591231_1074979.log)
```
  0:  ==========================================
  0:  MODEL SETUP took on mype=0 [seconds]
  0:  runtime setup total         1337.456
  0:   > runtime setup mesh       1.450488
  0:   > runtime setup ocean     0.4124953
  0:   > runtime setup forcing   3.6961141E-03
  0:   > runtime setup ice       1.0040575E-02
  0:   > runtime setup restart    1331.384
  0:   > runtime setup other      4.194682
  0:  ============================================
```
log file of the second run:
[pi_awicm3_tco95_core2_awicm3_compute_18600101-18691231_1076863.log](https://github.com/esm-tools/esm_tools/files/9403283/pi_awicm3_tco95_core2_awicm3_compute_18600101-18691231_1076863.log)
```
  0:  ==========================================
  0:  MODEL SETUP took on mype=0 [seconds]
  0:  runtime setup total         6.276999
  0:   > runtime setup mesh       1.795660
  0:   > runtime setup ocean     0.3997563
  0:   > runtime setup forcing   3.7931339E-03
  0:   > runtime setup ice       8.6037908E-03
  0:   > runtime setup restart   0.1019567
  0:   > runtime setup other      3.967230
  0:  ============================================
```

**System (please complete the following information):**
 - Supercomputer: levante
 - Version: 6.12.5

Actually, this problem appears in almost every awicm3 version/esm_tools/hpcs.
