### ISSUE TITLE
AWI-CM1 in Levante suddenly stops

### ISSUE THREAD

**Issue by antoniofis10000** [esm-tools/esm_tools#807]
Dear Developers.
I do not know why my AWI-CM1 runs in Levante suddenly stop without any apparent reason. This happens in two contexts.

The first is when I try to run a two months extension (same issue in Mistral), see for example: /work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/OctoberNovember2020NudgingOldE4. It seems the model suddenly stops after one month, so if I do not kill the process, it will continue running without any advance. Therefore I need to do monthly restarts (OctoberNovember2020NudgingOldE41Month), which is suboptimal.

The second one is when I try to run the model for a few days. It runs for only one day (/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/1Dayv3) but when I try to run it for 4 (/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/4Daysv1), 5 or 16 days (/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM16Daysv1) it stops on day 2.

Thanks in advance.
Best wishes,
Antonio.

**Comment by pgierz** [comment]
Moin Antonio

That in both cases sounds like a funky and badly configured namelist. Since you are using AWICM1, that will be ECHAM. Can you post the dt start, dt stop, lresume, putrerun and putdata settings? 

I'll also have some time to look in detail, but not until Thursday I'm afraid. 

Best
PG

**Comment by antoniofis10000** [comment]
In both cases it seems these parameters are correct (no reason to stop the simulation I think). 
In the first case (run stopped after one month instead of running for two months) according to: `/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/OctoberNovember2020NudgingOldE4/run_20201001-20201130/config/OctoberNovember2020NudgingOldE4_finished_config.yaml`
These parameters are:
```yaml 
               dt_resume:
                - 2020
                - 10
                - 1
                  dt_stop:
                - 2020
                - 12
                - 1
                lresume: true
                putrerun:
                - 2
                - months
                - first
                - 0
                putdata:
                - 1
                - hours
                - first
                - 0
 ```
In the second one (run for few days stopped after 2 days) for example for the `/work/ab0995/from_Mistral/ab0995/a270148/esm-experiments/AWICM/16Daysv1` simulation these parameters are (extracted from the same file as above):
```yaml
                dt_resume:
                - 2019
                - 1
                - 1
                dt_stop:
                - 2019
                - 1
                - 17
                lresume: true
                putdata:
                - 1
                - hours
                - first
                - 0
                putrerun:
                - 16
                - days
                - first
                - 0
```

Thanks.
Best wishes,
Antonio.
