### ISSUE TITLE
Renaming of runoff mapper grids not possible for master branch

### ISSUE THREAD

**Issue by fernandadialzira** [esm-tools/esm_tools#860]
AWI-CM3 master is now updated to the ECE4 version of the `openIFS` code. For the runoff mapper to work according to the naming of the ECE-EARTH community, the rnfa grid needs to be named `RFNA`, instead of `RfnA`, as it was previously. To do so, I tried adding such a grid only for the `master` branch:

```
choose_general.version:
                "master":
                        add_grids:
                                rnfa:
                                        name: RNFA
                        add_namelist_changes:
                                namelist.runoffmapper:
                                        NAMRNFMAP:
                                                LCalvingEnthalpy: True
```
However, the model would still only try to find the RnfA grid, leading to an error. The only way I could overcome this was to do a check run with

```
rnfmap:
    grids:
        rnfa:
            name: RNFA
```
on the run script. After this then a standard simulation could work.

Just a change in the chose-blocks should be enough for the model to look for RNFA grids.

I also tried to do `grids:`, instead of `add_grids:`, but I got an error message saying I could not do so, and that I should use `add_`.

Supercomputer: `Juwels`
ESM-tools branch: `release v. 6.17.2`
AWI-CM3: `AWI-CM3-master`

**Comment by mandresm** [comment]
Hi @fernandadialzira,

Thanks for reporting this issue. Could you please provide a runscript for me to reproduce the error?

Thanks!

**Comment by fernandadialzira** [comment]
> Hi @fernandadialzira,
> 
> Thanks for reporting this issue. Could you please provide a runscript for me to reproduce the error?
> 
> Thanks!


The script is:
`
/p/project/chhb20/fmatos/runtime/awicm3-master/runscript_testing/awicm3-master-juwels-TCO95L91-CORE2.yaml 
`
The part where I chose the grid is commented out.

**Comment by mandresm** [comment]
After adding the following lines to `awicm3.yaml` in the `rnfmap.choose_general.version."master"`:
```yaml
                        add_grids:
                                rnfa:
                                        name: RNFA
```

I can report that I cannot reproduce the error, neither with a check run or an actual run. Running the runscript provided (with the user modifications) the namcouple file ends up with an `RNFA` grid in all cases. Further debugging requires exploration of your local changes with potentially `git diff`.
