### ISSUE TITLE
default GAUSWGT remapping parameters not working for high resolution configuration

### ISSUE THREAD

**Issue by mzapponi** [esm-tools/esm_tools#898]
The default parameters for the Gaussian weighted remapping in the oasis3mct coupling methods are:

nb_of_neighbours: 25
weight: "0.1"

and are those fitting for lower resolution but not working for high resolution configuration. 
In the latter case 

nb_of_neighbours: 9
weight: "2"

should be set in the runscript in oasis3mct section.

**Comment by mandresm** [comment]
Hi @mzapponi,

I see what you mean, but what would be the expected behavior? what would you like us to fix?

**Comment by mzapponi** [comment]
Hi @mandresm, 

I think @JanStreffing's idea was to set up a switch that sets the parameters depending on the resolution used. 
He wanted me to open the issue so that he will remember to fix this at one point.

**Comment by mandresm** [comment]
Makes sense. Within the `awicm3.yaml` that could be set in the following way:
```yaml
oasis3mct:
    # Defaults
    nb_of_neighbours: 25
    weight: "0.1"
    
    # Switch for high resolution
    choose_oifs.resolution:
        <high_resolution_names>:
            nb_of_neighbours: 9
            weight: "2"
     
    # Call the variables within the remapping syntax
    coupling_methods:
        <remapping_method_of_your_choice>:
            nb_of_neighbours: ${nb_of_neighbours}
            weight: ${weight}
```

Or something on those lines.
