### ISSUE TITLE
postprocessing/subjob example needed

### ISSUE THREAD

**Issue by chrisdane** [esm-tools/esm_tools#960]
**Request/contribution description**
I am confused by the documentation on how to set up post-processing jobs/subjobs as e.g. here: https://esm-tools.readthedocs.io/en/latest/workflow.html?highlight=tidy#example-1-adding-an-additional-postprocessing-subjob:
```
echam:
        [...other information...]

        workflow:
                next_run_triggered_by: tidy

                subjobs:
                        my_new_subjob:
                                nproc: 1
                                run_after: tidy
                                script_dir:
                                script:
                                call_function:
                                env_preparation:
```
My question are:
- why is this in a specific model section (here echam)? 
- are both `next_run_triggered_by: tidy` and `run_after: tidy` necessary? Whats their difference?
- same for `script_dir` and `script`; why both?
- what are `call_function` and `env_preparation`?
- can't `nproc` be provided by e.g. a usual sbatch-header in the `script` itself?

I would find an explicit example very helpful.

Thanks a lot and cheers,
Chris

**Comment by nwieters** [comment]
Hi @chrisdane,

as a first reply to your issue.

 I followed the exercise in the ESM-Tools workshop (https://github.com/esm-tools/workshops/blob/main/202207_AWI_ESM-Tools/exercises/7.5_workflow_manager.md see the solution). 

And this worked for me as a first try:

```
flow:
    workflow:
        next_run_triggered_by: tidy
 
        subjobs:
            my_new_subjob:
                batch_or_shell: batch
                order_in_cluster: concurrent
                run_on_queue: ${computer.partitions.pp.name}
                nproc: 1
                run_after: tidy
                script_dir: "/work/ab0995/a270089/myrunscripts/"
                script: "hallowelt.sh"
                submit_to_batch_system: True
```

I placed this in a runscript as a new component. What also worked is to put everything starting from `workflow` in another component, as you mentioned in your issue. I also do not understand why this needs to be in a component.
I also had the same questions about the keywords as you mentioned. I agree that this needs to be improved in the documentation with some more examples.

If you have any other suggestions for the workflow manager, please also add them as a comment to the following discussion #1023. Thank you.
